### ISSUE TITLE
Scala Kinesis Enrich: fix checkpointing

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1467]
See @kazjote's explanation here: #1418

**Comment by fblundun** [comment]
The Amazon Kinesis Connector Library configures the Kinesis client to call processRecords even if the list of records to process is empty (i.e. no records have appeared in the stream since the last batch were processed). This enables it to flush the buffer at regular intervals without needing to create a new thread to schedule the flush.

Our planned approach has the flaw that if the input stream dries up, processRecords stops getting called and the buffered enriched events never get flushed (since the maximum time between flushes only gets checked whenever processRecords is called). `callProcessRecordsEvenForEmptyList` provides a solution to this problem: once the incoming stream dries up, we can still keep checking whether the maximum time between flushes has been exceeded.

**Comment by alexanderdean** [comment]
Sounds good Fred - what is the status/origin of `callProcessRecordsEvenForEmptyList`?

**Comment by fblundun** [comment]
It's a setting for the KinesisClientLibConfiguration class from the Kinesis Client Library.

**Comment by fblundun** [comment]
[This comment](https://github.com/awslabs/amazon-kinesis-client/blob/0fc90ff7878a19016c2663afdf3b78f007f63d81/src/main/java/com/amazonaws/services/kinesis/clientlibrary/interfaces/IRecordProcessorCheckpointer.java#L33-L35) suggests checkpointing about every 5 minutes, which is a lot less frequently than Scala Kinesis Enrich does. But I haven't encountered any ThrottlingExceptions and the Amazon Kinesis Connector Library makes no attempt to prevent them by checkpointing infrequently, so it may not be an issue.

**Comment by alexanderdean** [comment]
I think we should be okay - checkpointing is against DynamoDB which is pretty responsive...
