### ISSUE TITLE
Scala Common Enrich: update bad rows to include timestamp

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1577]
Probably some kind of failed_at timestamp

**Comment by fblundun** [comment]
[Here](https://github.com/snowplow/snowplow/commit/61254e5431866f6556c4a85531c0bcaa56c11d41) in the Scala Stream Collector we are using a formatted timestamp rather than a simple Unix timestamp for bad rows. Is this so that Elasticsearch recognizes them as timestamps? And if so should we be doing the same thing in Common Enrich?

**Comment by jbeemster** [comment]
We should be now yes, have not pushed the formatting to the other apps yet.

**Comment by alexanderdean** [comment]
Cool, thanks for clarifying!

**Comment by fblundun** [comment]
This breaks some of the existing tests in Hadoop Enrich that don't expect a timestamp field in bad row JSONs. Are we going to have a new Hadoop Enrich version as part of this release?

**Comment by alexanderdean** [comment]
Hey @fblundun - can you create a ticket to reflect this in Hadoop #1? We'll put this into the next Hadoop release, but it won't probably be the same release as Kinesis #6...

**Comment by fblundun** [comment]
Done!

**Comment by jbeemster** [comment]
Hey @fblundun did we come to a conclusion on whether or not the badrow timestamp should be formatted properly.  I added formatting to the stream collector but not sure anymore if this had to be the case for everywhere?

**Comment by alexanderdean** [comment]
Badrow timestamp should be a JSON-Schema compatible datetime

**Comment by jbeemster** [comment]
Thanks Alex will make sure that that is the case.
