### ISSUE TITLE
Scala Common Enrich: add validation that collector_tstamp is set and valid

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1611]
Very occasionally it isn't (with Clojure Collector), which is super-weird and fails a load.

/cc @yalisassoon

**Comment by alexanderdean** [comment]
Here is a value which is illegal: "-0025-01-01 23:01:01.000"

**Comment by fblundun** [comment]
You can get the leading hyphen by using a date that is BC ([source](http://stackoverflow.com/questions/13809682/jodatime-parsing-dates-with-leading-hyphens)). Although I don't know how we could have ended up with such a timestamp.

My plan is to return a `Failure` if the collector_tstamp is not set at all or if the result of `toTimestamp` starts with a hyphen, and a `Success` otherwise.

**Comment by alexanderdean** [comment]
Sounds good to me

**Comment by fblundun** [comment]
Presumably we should validate that all timestamp fields aren't negative? (e.g. it would be possible for somebody using the Python Tracker to set a negative dvce_tstamp.)

**Comment by alexanderdean** [comment]
Yes sounds wise!
