### ISSUE TITLE
Scala Common Enrich: decide what to do with column truncation code

### ISSUE THREAD

**Issue by yuvalherziger** [snowplow/snowplow#1659]
_Was_: Scala-common-enrich MaxJsonLength not configurable

Hi,
It could be useful to have MaxJsonLength on Scala-common-enrich configurable through Emr-Etl-Runner. Currently hard-coded to 15000, which is insufficient in cases where the payload exceeds this limit.

https://github.com/snowplow/snowplow/blob/80236a1b5de2bda683a07b48acf999f0f1c4218a/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/EnrichmentManager.scala#L102

Thanks!

**Comment by alexanderdean** [comment]
Hey @yuvalherziger ! This is a really interesting ticket. The hard-coded 15000 is designed to ensure that no truncated JSONs will get loaded into atomic.events. Even a single truncated JSON could break Redshift's JSON functions.

You raise a very good point: if you have shredding setup, then you are much more interested in having oversized JSONs successfully shredded thru to Redshift, and you won't care if the raw JSON fields in atomic.events are truncated.

The underlying problem here is that Snowplow's enrichment process is somewhat complected with the Redshift-specific storage code: the truncation code you mention should really be in a Redshift-specific component, not in the enrichment step.

I'm updating the ticket name so that we can give this further thought...

**Comment by yuvalherziger** [comment]
Hi @alexanderdean , inserting, thanks for the information and the correction.
So since we've been working with PostgreSQL (for now), we may want to build scala-common-enrich and scala-hadoop-enrich with our own tweak to the size limit.
We've also noticed now that Kinesis has a hard limit of 50KB per record, that's also interesting in that respect.
Generally speaking, I acknowledge the fact that web tracking should remain on a strict diet, but it's  somewhat troubling to know that when a customer insists on sending over long lists of attributes with an event's context, it may be a risky. I will stay tuned, thanks again for the info!

**Comment by alexanderdean** [comment]
Hi @yuvalherziger - yes, the 50kb limit on Kinesis is a bit of a pain, especially as we can't subdivide an event further without making things hugely complicated...

**Comment by alexanderdean** [comment]
My preference is to remove the truncation code in its entirety, and bring it back on a per-db basis as needed in the future. This may lead to some breakages on the Postgres side but would be much better for Redshift (which supports automatic truncation of columns on load).

**Comment by alexanderdean** [comment]
See also: #1731

**Comment by fblundun** [comment]
In R73, the column truncation code (which is only really needed for PG anyway) has moved from Hadoop Enrich (and by implication Kinesis Enrich) to Hadoop Shred. This means that the enriched event stream coming out of Kinesis Enrich will no longer have its JSON fields truncated (as of R74 - the Kinesis follow-up to R73).
