### ISSUE TITLE
Scala Kinesis Enrich: explore more succinct logging in case of failure

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1723]
If we are putting too fast, we get a bad log line for every row currently.

**Comment by fblundun** [comment]
The reason for this is that Kinesis gives each failed record its own error message, so different records in a batch could theoretically be rejected for different reasons.

We could log individual failures at a lower level so you aren't forced to see them.

**Comment by alexanderdean** [comment]
Let's push this one back..

**Comment by fblundun** [comment]
The offending line is [here](https://github.com/snowplow/snowplow/blob/b772f6e089bb9e0b3bdbed93a4ab18902c4f1a4a/3-enrich/stream-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/kinesis/sinks/KinesisSink.scala#L277).

Possibilities:

* Change that particular log level from error to debug
* Log at the error level just a list of unique error codes (each together with an error message) in the responses to events in the batch, rather than all the error codes and messages.

**Comment by alexanderdean** [comment]
How about option 2 but with a count against each code?

**Comment by fblundun** [comment]
Sounds good! I have implemented it that way with messages like this:

```scala
error(s"$count records failed with error code ${errorCode}. Example error message: $sampleMessage")
```

**Comment by alexanderdean** [comment]
Nice
