### ISSUE TITLE
Scala Hadoop Shred: add ability to process LZO stored files

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1733]
So potentially we could archive enriched events from the Kinesis enricher and not have to perform enrichment in batch as well (i.e. only shredding in batch)...

**Comment by fblundun** [comment]
This would probably involve moving [FixedPathLzoRaw](https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-hadoop-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich.hadoop/FixedPathLzoRaw.scala) to Common Enrich, since there's no need to have it in both Hadoop Enrich and Hadoop Shred.

**Comment by alexanderdean** [comment]
Makes sense...

**Comment by alexanderdean** [comment]
Note that following https://github.com/snowplow/kinesis-s3/pull/43 this might not be super-necessary.

**Comment by fblundun** [comment]
Following discussion, let's close this one. We can test out kinesis-s3 -> s3.gz -> hadoop shred -> redshift.
