### ISSUE TITLE
AWS Kinesis record size increase

### ISSUE THREAD

**Issue by grzegorzewald** [snowplow/snowplow#1736]
On 2nd of Jun AWS Kinesis have increased record size to 1 MB, therefore Kinesis stack limit as well as used libraries should be upgrade accordingly (in my opinion this would remove all the record size issues observed in Snowplow).

Source: https://aws.amazon.com/blogs/aws/amazon-kinesis-update-simplified-capture-of-streaming-data/

**Comment by alexanderdean** [comment]
Thanks for raising @grzegorzewald ! Great announcement by AWS there.

@fblundun - I remember us making the Kinesis record size hocon-configurable, but can't seem to find it in the collector hocon. Please advise?

**Comment by grzegorzewald** [comment]
@alexanderdean: as far as I see in sources, If the record size is greater than 50 KB, it is rejected and not send to Kinesis. The limit is hardcoded (at least in Enrichment and ELasticsearch Storage in r65).

**Comment by alexanderdean** [comment]
Yeah, a lot of work has been done on that stuff in Kinesis #6... Fred is back next week, he will update us...

**Comment by fblundun** [comment]
The thing that we made configurable was the maximum total size of a PutRecords rather than the maximum size of an individual record.

I'm glad that the individual record size limit is increasing - I'll incorporate it into kinesis-6 milestone.

Should we actually try to pre-empt Amazon and make the maximum record size configurable too? It seems unlikely to me that they will change it again any time soon...

**Comment by alexanderdean** [comment]
Thanks @fblundun - I would add make maximum record size configurable in Kinesis #8. You're right, not a priority as 1Mb is large and they are unlikely to update soon...
