### ISSUE TITLE
Azure support for Snowplow [discussion]

### ISSUE THREAD

**Issue by thomaswrenn** [snowplow/snowplow#1779]
Can someone implement support for running Snowplow on Azure?

**Comment by jpoon** [comment]
+1

**Comment by alexanderdean** [comment]
I think there are two ways we could implement Azure support:

1. It should be straightforward to run the planned Kafka+Samza version of Snowplow on Azure boxes. Then we could just implement support for [SQL Data Warehouse](http://azure.microsoft.com/en-gb/campaigns/sql-data-warehouse/) when that's available
2. We could create an "Azure idiomatic" version of Snowplow using [EventHub](https://msdn.microsoft.com/library/azure/dn789972.aspx)

Has anyone successfully used EventHub in the wild? It looks pretty immature compared to Kinesis and Kafka...

**Comment by jpoon** [comment]
Ooh, that sounds promising! How far along is the Kafka+Samza version? 

As @alexanderdean had mentioned, the other alternative is to support EventHub. My team has used EventHub successfully in the past pumping stuff in like logs and GPS data. I haven't personally used Kinesis so I can't compare.

If we can use the Kafka+Samza version, a good starting point might be to add support for sinking data to [Azure Blob Storage](https://msdn.microsoft.com/library/azure/dd179376.aspx) (Azure equivalent to S3). Azure Blobs also have an HDFS interface to which we can run Hive / Pig jobs on top of the blobs.

**Comment by alexanderdean** [comment]
Hey @jpoon ! EventHub looks interesting but I could only find .NET examples for it; we would need a JVM SDK for it to make it work with Snowplow.

The Kafka+Samza version is still currently on the drawing board - although we do have a branch with Kafka support for our Scala Stream Collector.

One potential architecture for Azure could be like this:

```
trackers -> Scala Stream Collector -> Kafka -> Kafka-Blob sink -> an Azure-friendly version of our existing Hadoop flow
```

I guess questions I would have:

* Is there an equivalent of Pinterest's [Secor](https://github.com/pinterest/secor) but for sinking from Kafka to Azure Blob Storage instead of S3?
* Our EmrEtlRunner Ruby (soon to be JRuby) app does a **lot** of Hadoop orchestration on Elastic MapReduce, using [Elasticity](https://github.com/rslifka/elasticity). What is the equivalent for programmatically orchestrating a Hadoop job on Azure? We would need a Ruby or JVM SDK here too

**Comment by jpoon** [comment]
As per the architecture you listed, just want to make sure we're on the same page with all our options: 

__Collectors__

* _Event Hub_: Data can be pushed into Event Hub through the REST API or via AMQP. [Apache Qpid](http://qpid.apache.org/) has a [JMS](http://qpid.apache.org/components/jms/index.html) component that we could use to pull data in and out. Also came across some examples [here](https://github.com/hdinsight/eventhubs-client).
* _Kafka_: If we use Kafka, it's not cloud-specific so we could run it on an Azure VM and start partying.

__Storage__

* _Azure Blob Storage_. I couldn't find an existing solution out there for sinking Kafka/Event Hub to Azure Blob Storage. If we can't find one, I don't foresee this being too difficult to implement. (famous last words? :P) 
* _SQL Data Warehouse_. Not entirely sure when public preview will be open. Might be a good goal in the long term? 
 
__Analytics/Compute__
* I haven't worked a whole lot with Hadoop. The Azure version of Hadoop is known as [HDInsight](http://azure.microsoft.com/en-us/services/hdinsight/) which is essentially repackaged Hortonworks Data Platform (HDP). Let me try to find out if there is something simliar to Elasticity.

**Comment by alexanderdean** [comment]
Hey @jpoon ! Thanks for the summary of options, very helpful. Some comments:

* EventHub - the hdinsight/eventhubs-client looks promising. Potentially we could embed that into the Scala Stream Collector, and then Snowplow raw events could be written straight to EventHub
* Kafka or EventHub -> Azure Blob Storage. Shame there isn't something already - it feels like this would be a good thing for Microsoft to build to encourage Azure adoption. A bit like Amazon's [amazon-kinesis-connectors](https://github.com/awslabs/amazon-kinesis-connectors) library. We have written [kinesis-s3](https://github.com/snowplow/kinesis-s3), somebody needs to write kafka-azureblob or eventhub-azureblob :-)
* SQL Data Warehouse - yes, having a horizontally scalable analytics database available is essential for a Snowplow user. How do we get on the private beta? :-)
* PostgreSQL - yes, PostgreSQL support is available. It will struggle with any serious event volumes, but it can be a good way of testing things.
* HDInsight - let me know when you know about orchestration tools. The other thing we lean on heavily is AWS's [S3DistCp](http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/UsingEMR_s3distcp.html), which is an Amazon fork of the regular Hadoop DistCp tool, which makes it easy to move data S3<>HDFS. I wonder if there's an equivalent in HDInsight?

**Comment by alexanderdean** [comment]
I've done some digging, and it looks like there is a .NET library for automating Hadoop jobs on HDInsight:

* https://hadoopsdk.codeplex.com/
* https://azure.microsoft.com/en-gb/documentation/articles/hdinsight-submit-hadoop-jobs-programmatically/#submit-mapreduce-jobs-using-hdinsight-net-sdk

**Comment by thomaswrenn** [comment]
Our use case:
I'm interested in trying out Snowplow but I want to do so in Azure because that's where we have a lot of free credits. 

What's the shortest path for me to do this on Azure?

We're a small team and just starting out with tracking user analytics so we want something quick to setup but where we'll own the data and will be easy to scale in the future without a migration.

**Comment by alexanderdean** [comment]
As per the above, it's not possible currently...

**Comment by jpoon** [comment]
* **Kafka or EventHub -> Azure Blob Storage**. Have you found that a lot of people persist the raw events from Kinesis straight to S3? What is the difference between Amazon's [version](https://github.com/awslabs/amazon-kinesis-connectors/tree/master/src/main/java/com/amazonaws/services/kinesis/connectors/s3) vs [snowplow](https://github.com/snowplow/kinesis-s3)? In any case, agreed that it would be useful code. I wouldn't mind giving a crack at it once we decide which direction to go -> Kafka vs Event Hub.
* **SQL Data Warehouse**. Let me poke around the company :)
* **HDInsight**. HDInsight has [native support for Azure Blob Storage](https://azure.microsoft.com/en-us/documentation/articles/hdinsight-hadoop-use-blob-storage/) (ie. no need to move it to an explicit HDFS store). Once the raw events are in Blob Storage, we can run MR jobs directly on top of it. As for management libraries, as you pointed out, there's the client [.net library](http://hadoopsdk.codeplex.com/wikipage?title=WebClient). Otherwise, as HDInsight deploys the Hortonworks Hadoop stack there is [Ambari](https://github.com/Azure/azure-content/blob/master/articles/hdinsight-hadoop-manage-ambari.md) and WebHCat out of the box. 

I think what @thomaswrenn may have meant is in consideration of the options above, quickest path to supporting Azure. In this case, it might mean adding support for kafka or event hub and then using the persisting that data to PostgreSQL? What do you think?

**Comment by thomaswrenn** [comment]
Yeah, sorry, I severely miswrote. I mean’t to phrase it as what the smallest set of implementations/ports would be to get something running on Azure like @jpoon said.

**Comment by alexanderdean** [comment]
Hey @jpoon, @thomaswrenn  ! No worries at all. Answers to your questions/comments:

> Have you found that a lot of people persist the raw events from Kinesis straight to S3?

Yes - at the moment we don't do loading of Redshift from Kinesis (only from Hadoop), so currently we recommend people sink the raw events to S3 and then run our Hadoop pipeline to load into Redshift as per [our latest release blog post](http://snowplowanalytics.com/blog/2015/06/16/snowplow-r66-oriental-skylark-released/#lambda)

In any case - yes archiving raw events is important to facilitate re-processing later; I explore this in [chapter 9](http://www.manning.com/dean/) in my book.

> What is the difference between Amazon's version vs snowplow?

Amazon's version is more of a toolkit (albeit with a sample application) - kinesis-s3 is a pre-built app which just needs a configuration file. Also, kinesis-s3 writes lzo-index files which are very Hadoop-friendly.

> HDInsight. HDInsight has native support for Azure Blob Storage (ie. no need to move it to an explicit HDFS store).

Ah okay. EMR has native support for S3 too - but moving to the cluster's HDFS with S3DistCp first makes processing much faster. Is that not the case with HDInsight?

> Otherwise, as HDInsight deploys the Hortonworks Hadoop stack there is Ambari and WebHCat out of the box.

Right - and now that the Snowplow Hadoop job runs on Hadoop 2.4.0 / YARN, we could probably submit the job using the [YARN Client](https://hadoop.apache.org/docs/r2.4.1/api/org/apache/hadoop/yarn/client/api/YarnClient.html)?

> quickest path to supporting Azure ... it might mean adding support for kafka or event hub and then using the persisting that data to PostgreSQL?

My gut says:

1. Scala Stream Collector with EventHub support via eventhubs-client
2. EventHub -> Azure Blob Storage sink app
3. Snowplow CLI app can submit Hadoop job to vanilla YARN cluster (#1792)
4. We extend our Redshift loading engine to also work with SQL Data Warehouse

This is the minimum number of moving parts which is still very horizontally scalable.

Postgres would be less work but it would be much less impactful - because nobody with serious event volumes can use Postgres with Snowplow. Also a powerful part of Snowplow is the custom shredding process which loads our event JSONs into dedicated tables in Redshift...

**Comment by thomaswrenn** [comment]
Do you have a recommended blog post or design document that explains the shredding?

**Comment by alexanderdean** [comment]
These are probably quite a good place to start:

* http://snowplowanalytics.com/blog/2014/07/09/snowplow-0.9.5-released-with-json-validation-shredding/
* https://github.com/snowplow/snowplow/wiki/6-Configuring-shredding

**Comment by jpoon** [comment]
> HDInsight + Azure Blob Storage

[Best practice](https://msdn.microsoft.com/en-us/library/dn749864.aspx#_Data_storage) is to have the data in Blob Storage. Azure did a massive amount of network upgrades a few years ago such that for MR jobs, perf characteristics for accessing data in Azure Blobs was near identical to the cluster's HDFS.

> HDInsight + YARN

Totally :+1:. It's probably best to avoid any specific client libraries where we can such that anything we do here can also apply everywhere else.

> PostgreSQL

Fair enough.

**Comment by jpoon** [comment]
To throw another option into the ring, an alternative to building an explicit app for EventHub->Azure Blob Storage sink is to leverage another SaaS offering from Azure: [Stream Analytics ](https://azure.microsoft.com/en-us/documentation/articles/stream-analytics-key-concepts/). We can use it to (1) read from event hub, (2) do some sort of processing, if any, (3) push it to azure blob storage. 

With that in mind, we could build snowplow support for:

```
event hub -> stream analytics -> azure blob storage
                              -> sql data warehouse
```

**Comment by alexanderdean** [comment]
Hmm - streaming analytics doesn't look like you can execute arbitrary code. We need a runtime (whether Hadoop, Samza or something else) where we can embed all our enrichment and validation logic :-)

**Comment by philbritton** [comment]
Azure Data Factory looks like the 'azure way' for managed ETL's, could this be a piece of the puzzle? https://azure.microsoft.com/en-us/services/data-factory/

**Comment by alexanderdean** [comment]
Potentially @philbritton ! But these sorts of managed cloud ETL services tend to be too opinionated to make a port of Snowplow straightforward...

**Comment by rgknp** [comment]
I would really like Snowplow support in Azure. 
Now Storm and Spark Streaming is available as part of Azure HDInsights. Also there is MPP version of Postgres (XtremeData) available in Azure Marketplace. So you could technically use Redshift loading engine with XtremeData without huge changes.

So probably this could be a viable alternative.

event hub -> storm/spark streaming -> azure blob storage
                                                         -> Xtremedata (Postgres MPP)
                                                         -> azure SQL Datawarehouse

Can't wait to see Snowplow on Azure..

**Comment by alexanderdean** [comment]
Hey @rgknp - we would love to see Snowplow on Azure too! How do we make this happen? Storm/Spark Streaming is a nice idea but we always want support for our standard batch flow so that we can enable users to perform full-archive re-processing (e.g. when we introduce new enrichments or update the enriched event format).

So we need to support at a minimum:

```
collector -> event hub -> azure blob storage -> hadoop -> azure sql data warehouse
```

With this in mind - has Azure made any progress in the last 12 months with providing a standard component for sinking an EventHub into Azure Blob Storage (think Secor but for Azure)? We are only a small team and don't have the bandwidth to build these kinds of generic components for Azure at this time...

**Comment by rgknp** [comment]
Yes, Azure now has EventProcessorHost component for receiving events from Event Hub. Below URL has complete implementation including code.

[(https://azure.microsoft.com/en-us/documentation/articles/event-hubs-csharp-ephcs-getstarted/)]

**Comment by alexanderdean** [comment]
Hey @rgknp - the EventProcessorHost looks pretty low-level. AWS provide the [kinesis-connectors](https://github.com/awslabs/amazon-kinesis-connectors) project to make things like Kinesis->S3 straightforward. What's the Azure equivalent?

**Comment by markusahlstrand** [comment]
@alexanderdean Not sure it fits your scenario but we're using stream analytics to stream data from event hubs to blob/table storage.

**Comment by alexanderdean** [comment]
Thanks @markusahlstran - that's helpful to know. I read somewhere that Stream Analytics has to deserialize the individual records before working with them - isn't that rather inefficient if we just want to write them to Blob Storage?

**Comment by rgknp** [comment]
@alexanderdean what is the performance you are looking for? In Stream Analytics you could do "select * from <EventHubSource> and output it to blob storage. Each streaming unit can give throughput of 1 MB/sec. You can add streaming units to scale up to 1GB/Sec.

**Comment by alexanderdean** [comment]
That sounds good @rgknp - does it work with Thrift? How are records written to Blob Storage - presumably N incoming records are written to each file - what is the file format for storing N records?

**Comment by rgknp** [comment]
@alexanderdean Stream Analytics supports Avro, CSV and JSON file formats. I am not aware of Thrift support. But you may want to look at Bijection APIs [https://github.com/twitter/bijection](url) for Thrift -> Avro conversion if needed.
Records will be written to blobs which can be in user defined containers. You could define path prefix, date and time format if you want data to be split into separate blobs. Each blob can hold max 1TB of data so it is a good idea to split records based on some kind of distribution. Splitting blobs based on date and time is most popular. More details can be found here [https://azure.microsoft.com/en-us/documentation/articles/stream-analytics-define-outputs/](url)

**Comment by rgknp** [comment]
@alexanderdean I found kinesis-connector like libs for Azure. These are called data-pipeline libs. Written and supported by Microsoft.
[https://github.com/mspnp/data-pipeline](url)
[https://github.com/mspnp/data-pipeline-storm](url)

**Comment by alexanderdean** [comment]
Great find @rgknp !

**Comment by rgknp** [comment]
I am glad that worked out. Can't wait to have Snowplow on Azure.
@alexanderdean do you have a timeframe for this?

**Comment by alexanderdean** [comment]
No timeframe, sorry - getting Kafka support for Snowplow is our first priority.

**Comment by rgknp** [comment]
@alexanderdean Do you have/plan to have Azure in your roadmap?

**Comment by alexanderdean** [comment]
Hi @rgknp ! It's not yet on the roadmap. We are currently still at the point of trying to identify internal sponsors at Azure for our port. But did have a great meeting @ MS last week in London where we went through Azure SQL DW - very cool tech...

**Comment by alexanderdean** [comment]
Sounds good!

**Comment by alexanderdean** [comment]
Discussion migrated to http://discourse.snowplowanalytics.com/t/porting-snowplow-to-microsoft-azure/1178
