### ISSUE TITLE
Scala Common Enrich: etl_tstamp in Enrichment Manager should be a Joda DateTime not a String

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#1841]

**Comment by alexanderdean** [comment]
Pushing back to R69

**Comment by alexanderdean** [comment]
This will ensure better type safety...

**Comment by fblundun** [comment]
The nice thing about keeping this a String rather than a DateTime in the EnrichmentManager is that it means we don't need to convert the DateTime to a Redshift-compatible string with every event we process.

Instead we could make EtlPipeline a class rather than an object and give it a constructor with a DateTime etlTstamp parameter.

**Comment by alexanderdean** [comment]
Hmm - how would the EtlPipeline as a class sit with Kinesis Enrich? Given that the output for Common Enrich won't be Redshift-formatted in a while anyway, I'm not too stressed about the conversion (in other words, soon we will have lots of conversions anyway).

**Comment by fblundun** [comment]
With Kinesis Enrich you would create a new EtlPipeline with a new timestamp (or update the timestamp of the existing EtlPipeline) for every call to GetRecords.

But proportionally, the effect on performance should be pretty small, so maybe we just make it a DateTime and do the conversion in each call to `enrichEvent`.

**Comment by alexanderdean** [comment]
Thanks for clarifying - yep - I think let's just make it a DateTime...
