### ISSUE TITLE
Kinesis Elasticsearch: automatic rotation of index names

### ISSUE THREAD

**Issue by sdboer78** [snowplow/snowplow#1886]
Please add an option to the kinesis-elasticsearch-sink so every day/week/month year can start with a new index. Like a logrotate.

Config example:
location {
  index: "snowplow"
  type: "enriched"
  rotate: "day" (options: none/day/week/month/year)
}

The index name can be like this: 
"snowplow_20150708" in case of rotate=day
"snowplow_2015_w13" in case of rotate=week
"snowplow_2015_m7" in case of rotate=month
"snowplow_2015" in case of rotate=year
"snowploy" in case of rotate=none (or not configured)

**Comment by alexanderdean** [comment]
Hey @jbeemster - I know you've looked into this. Would this work as something inside the sink itself, as @sdboer78 suggests?

**Comment by christoph-buente** [comment]
As the peeps from elastic.io highly recommend to use data-based index names, this would come in very handy. Kibana is made to handle with those types on indexes out of the box. And it also makes it much easier to delete old data, by just killing the full index.

**Comment by christoph-buente** [comment]
@alexanderdean It is usually not a problem with several sink instances talking to a single index. It's actually how it is done today. But as the hour or day turns, a new index would need to be created automatically. Which leaves the old index read-only. And it would also be better performance when re-sharding happens. We have 86GB of data from 72h of event tracking. Re-sharding is really painfull and slow. A big 👍  for this issue :)

**Comment by jbeemster** [comment]
I think this could become part of the sink quite happily.  Each sink would be attempting to make the same requests but only one would be able to successfully hit the API in time (this claim will involve some testing).  

Whichever sink gets the 200 response will then be elected to:

* Create the new index
* Re-alias to the new index so that new data is sent to the correct place
* Forcemerge the old index; this makes seek time much faster on the old index as there is only one segment and all marked for deletion files will be removed.

We could also add options to automatically backup to a specific target (S3 to begin with) and how many old indexes to keep around at a time.

**Comment by alexanderdean** [comment]
This sounds great - let's bring this forwards ;-)[](url)

**Comment by alexanderdean** [comment]
Bringing forwards

**Comment by alexanderdean** [comment]
We should auto determine shard count for new index

**Comment by alexanderdean** [comment]
What if we build instead a CLI wrapper around Curator: https://www.elastic.co/guide/en/elasticsearch/client/curator/4.0/about-origin.html We can still do the cool stuff like assess event volumes and use this to auto-determine shard count...

**Comment by alexanderdean** [comment]
Stubbed https://github.com/snowplow/elasticsearch-housekeeper

**Comment by christoph-buente** [comment]
What about getting the feature implemented first, learn from it, and then add stuff on top like auto-shard discovery and such things? The number of shards are in the config file already. But the immediate benefit from this feature is a much more performant and easily reshardable ES cluster. Resharding a 30GB or even couple of hundred GB in one single index is a real pain.

**Comment by jbeemster** [comment]
Hi @christoph-buente, the idea behind creating elasticsearch-housekeeper rather than adding this functionality directly into the sink is that:

1. This functionality already exists in Curator, which also has versions with compatibility for all versions of Elasticsearch - which we then do not need to support.
  - It has support for daily indexing and re-aliasing already
2. These features are also required for the batch loading where we allow for loading of bad rows into Elasticsearch from EMR.
3. Putting a daily housekeeping process inside the sink makes the sink harder to test and reason about.

What you are suggesting as it being as an external scheduled job can already be done with Curator.  You can also already point the sink at an alias rather than a specific index.  So we end up gaining very little by including this directly into the sink.  You would just need to ensure that your cluster was prepared prior to running the sink.

Any missing functionality or anything that is specific to Snowplow can then be added on top of Curator in our app.

**Comment by christoph-buente** [comment]
Thx @jbeemster for the explanation. Makes total sense! I know about curator, but i wasnt aware it had out of the box index swapping capabilities.

**Comment by christoph-buente** [comment]
Hey @jbeemster,

we implemented an alias and index rotation scheme using curator. But there is an issue with it, that I'm not sure how to resolve.

We use hourly indeces due to our high write volume. And we have an anlias pointing to the current hour's index. Now let's say the kinesis-es-sink falls behind, because of too much traffic. Then it would write last hours events into this hour's index. If you look in Kibana on the full timeline, you don't see a difference, but if i zoom in last hours time frame, i see no data, cause it actually lives in this hour's index.

Is there a way around it?

**Comment by jbeemster** [comment]
Hey @christoph-buente unfortunately the sink only knows about what you have pointed it to.  So when you change the alias it will start sending to the new index.

You might be able to mitigate these effects by either having longer indexes (6/12/24 hours) or by writing a script to halt the rotation until the Sink has caught up.  You could check the most recent record against the current time and only rotate at this point.

**Comment by christoph-buente** [comment]
That is a possible workaround. But coming back to the original cause of this ticket: the kinesis-es sink has the notion of the timestamp already. If it had the notion of the index pattern, it could decide event by event, in which index to writen. And what is more: on re-running raw logs from the past, that would work too. 

I'm not saying anymore, that we should handle the indexes from snowplow. But making it aware of an index pattern could be helpful still.

**Comment by alexanderdean** [comment]
Hey @christoph-buente - what you're saying makes sense. If we have an ES with an index being actively partitioned, then it makes sense for the Kinesis ES sink to be "partition-aware" and load into the correct partition.

Would you be able to share the partitioning rules that you are using with curator? Are they defaults or customized by you?

**Comment by christoph-buente** [comment]
We are using an hourly index with 2 partitions each and a replication factor of 1. That means for every hour there are 4 shards (2x shard 0 and shard 1)
The naming pattern is something like: useful-name-YYYY.MM.DD.HH

We are using a bash script which runs every hour minute 0, which does the following:
* create the index for the current hour including mapping and so on
* add the alias from (the kinesis-es.conf index name) to this index
* remove the alias from last hour's index
* delete indexes older than our retention threshold
* create next hour's index, just to make sure it there, on the brink of next hour :)

**Comment by BenFradet** [comment]
migrated to: snowplow/snowplow-elasticsearch-loader#24
