### ISSUE TITLE
Scala Stream Collector: restrict access?

### ISSUE THREAD

**Issue by jramos** [snowplow/snowplow#1969]
Is there any known or preferred way to globally restrict access to the collector endpoints? I know I can filter Events from the stream at a later point, but I'd prefer requests from "unauthorized" trackers to not ever be written to Kinesis. I can envision how this would work server-side, where secrets can be protected, but I'm at a loss when it comes to the JS and No-JS trackers.

Any ideas?

**Comment by alexanderdean** [comment]
The problem is determining if an event is "unauthorized" or not. Our view is that you are better off determining that downstream where you have an audit trail for the events and if you make a mistake in your categorization, you can correct it (because you still have the raw events archived in S3).

See also: #1139

**Comment by jramos** [comment]
:+1:
