### ISSUE TITLE
Scala Kinesis Enrich: bump Scala Common Enrich to 0.22.0

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2033]

**Comment by chuwy** [comment]
I think we also will need to remove `toTimestamp` [invocation](https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-kinesis-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/kinesis/sources/AbstractSource.scala#L187) as `EtlPipeline.processEvents` now accepts `DateTime` instead of `String`.
