### ISSUE TITLE
Scala Hadoop Enrich: should all bad rows for a run have the same failure_tstamp?

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2062]
We give the same etl_tstamp to all good rows for a run. We could do something similar for bad rows.

One advantage: it would help with Elasticsearch deduplication (see #2060)

**Comment by alexanderdean** [comment]
It's a good question! If bad rows were events (which they will become one day), then I would say that failure_tstamp would become the true_tstamp for the event, rather than the etl_tstamp. I agree however that it would be very helpful to have the etl_tstamp in the bad row event as well.

Therefore, I would not set failure_tstamp to etl_tstamp, but I think there is a good case for:

1. Accelerating turning the bad rows into proper events, _and/or_
2. Attaching etl_tstamp to the bad rows and renaming failure_tstamp to true_tstamp

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/119
