### ISSUE TITLE
Scala Kinesis Enrich S3 storage via AWS Kinesis Firehose

### ISSUE THREAD

**Issue by xkidro** [snowplow/snowplow#2165]
Kinesis now has a sink built in called Kinesis Firehose.

My question is the events format that is used in Kinesis enriched good stream the same as the one from Kinesis LZO S3 sink ( https://github.com/snowplow/snowplow/wiki/kinesis-lzo-s3-sink-setup ) or https://github.com/snowplow/snowplow/wiki/setting-up-EmrEtlRunner ?

If it is it could eliminate the need for a S3 sink and Redshift sink all together.

**Comment by alexanderdean** [comment]
Hey @xkidro - using the Kinesis Firehose instead of the kinesis-s3 app is an interesting idea! It's not something we have the bandwidth to investigate at this time.

If you get a chance to experiment with this approach, please update this ticket with your findings!

**Comment by bcharp** [comment]
Any update ? I'm interested too.

**Comment by alexanderdean** [comment]
Hi @bcharp - using Kinesis Firehose instead of kinesis-s3 is not something we are actively exploring.

I don't believe Kinesis Firehose can work with binary formats like Thrift - if I am wrong please let me know. In the absence of that, we would have to re-engineer the Stream Collector, Hadoop Enrich and Stream Enrich to move to a textual format like JSON for raw events, and this would of course increase the size of our raw events in Kinesis and S3, plus slow down enrichment (because JSON de/serialization is slow).

Related, our kinesis-s3 output format is optimized for fast Hadoop processing - again we would lose this in the switch to Kinesis Firehose.

A Snowplow real-time topology ends up with a lot of different moving parts - porting to Firehose to remove one moving part doesn't feel like a win given the compromises we would have to make. But certainly happy to hear a counter-view...

**Comment by bcharp** [comment]
Well, it made sense in my mind with this specific mindset : As snowplow is always using the most standard way to do things with AWS, Firehose is surely on the way to enable me to have a streaming pipeline directly from my events to Redshift. But, in fact, the more I read on the streaming pipeline, the more I believe that it's actually not made to insert data into Redshift.

**Comment by alexanderdean** [comment]
> As snowplow is always using the most standard way to do things with AWS

One of the nice things about AWS is that there isn't "the most standard way to do things" - instead AWS typically offers a variety of different strategies, which tend to vary based on ease of use vs configurability.

The trend with Snowplow is often to start with the easiest-to-use approach, and then move towards the more configurable approach as we outgrow the easiest-to-use approach. You can see this with collectors:

1. CloudFront Collector, super easy to use, very inflexible
2. Clojure Collector, still easy to deploy using Beanstalk, more functionality but no control over logfile rotation and some Beanstalk behaviors are a little mystical
3. Stream Collector - very flexible, not even AWS specific but can be deployed on AWS using ELB and an ASG

In terms of streaming events from the real-time pipeline into Redshift - this is something we are working on. We are doing a lot of work to extend Iglu and StorageLoader so that they can handle automatic table creation, table migrations etc. These are tough problems but will be very exciting to solve!

**Comment by johnrobertfitz** [comment]
It's kind of hacky, but I was able to get streaming to Redshift every minute by doing: 

Scala Collector -> Log File Buffer
Log File Buffer -> Scala Enrich
Scala Enrich -> Enriched Log Files
Eriched Log Files -> Firehose via Kinesis Firehose Agent

**Comment by alexanderdean** [comment]
Thanks for sharing @johnrobertfitz !

**Comment by harmy** [comment]
@johnrobertfitz Thanks for sharing, I am also intertested in this subject, would you please show me some more details? like how can scala enrich do with log file buffer?

**Comment by fingerco** [comment]
This is also a rough hack, but I thought I'd post it here in case it'd help someone towards their own solution. I was able to modify the kinesis-tee project to push (TSV -> JSON transformed) events to Firehose instead of pushing to another Kinesis stream:

https://github.com/snowplow/kinesis-tee/compare/master...fingerco:firehose

Which makes our current process:

Scala Collector -> Raw Kinesis
Raw Kinesis -> Scala Enrich
Scala Enrich -> Enriched Kinesis
Enriched Kinesis -> Kinesis Tee (JSON Transform)
Kinesis Tee -> Firehose
Firehose -> Redshift

**Comment by alexanderdean** [comment]
Thanks for sharing @fingerco !

**Comment by alexanderdean** [comment]
18 months later and Kinesis Firehose is still only available in 3 regions, closing

**Comment by jdub** [comment]
A year later, Firehose is available in [most AWS regions](https://aws.amazon.com/kinesis/data-firehose/pricing/), and there still seems to be some interest on the forums and elsewhere. Is this still a `wontfix`?

**Comment by alexanderdean** [comment]
That's right @jdub - Snowplow S3 Loader continues to be our focus.
