### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by 0xABAB** [snowplow/snowplow#2343]
In the thrift collector description there is a dead link pointed to by 
"Check for the newest version". 

One other question: I would be interested in at the very least running a collector on our own servers, i.e., not at Amazon. Is that even possible? The thrift collector seems to suggest that, but there is no documentation available for it. Can you give some context for running a self-contained setup?

**Comment by alexanderdean** [comment]
Hey @0xABAB - for support questions (your second paragraph - your first is fine), please ping the user group, https://groups.google.com/forum/#!forum/snowplow-user

**Comment by alexanderdean** [comment]
@ihortom - not sure if this refers to wiki documentation or repo (README) documentation...

**Comment by ihortom** [comment]
@alexanderdean Looks like it refers to [README](https://github.com/snowplow/snowplow/blob/64a789273047d33c186cf00e2a0d8aabe52339f3/2-collectors/thrift-schemas/README.md):

**Comment by alexanderdean** [comment]
You're right - thanks @ihortom . Putting this one in the appropriate milestone...

**Comment by ihortom** [comment]
@fblundun would you know the correct link? The doc anchor refs to the [broken link](http://maven.snoplow.com/releases/com/snowplowanalytics/snowplow-thrift-raw-event/). It could be just misspelt or else.

**Comment by fblundun** [comment]
The latest version is found at 

```
http://maven.snplow.com/releases/com/snowplowanalytics/snowplow-thrift-raw-event/0.1.0/snowplow-thrift-raw-event-0.1.0.jar
```

The original author probably thought that truncating that link to just

```
 http://maven.snplow.com/releases/com/snowplowanalytics/snowplow-thrift-raw-event/
```

would point to a listing of all the available versions, but apparently maven.snowplow.com doesn't work like that.

I think the simplest answer is to just remove point 2 and change `0.2.0` to `0.0.0` in point 3, since `0.0.0` is the version we actually use [here](https://github.com/snowplow/snowplow/blob/master/2-collectors/scala-stream-collector/project/Dependencies.scala#L61).

**Comment by alexanderdean** [comment]
Thanks @fblundun !

**Comment by ihortom** [comment]
Updated on local fork as per suggestion from @fblundun

**Comment by alexanderdean** [comment]
Fixed by @ihortom, closing
