### ISSUE TITLE
Clojure Collector: don't log OPTIONS requests

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2350]

**Comment by alexanderdean** [comment]
This would be complex given the architecture of the Clojure Collector - where the actual logging is performed by the Tomcat AccessLogValve, rather than by the collector itself.

Given that we plan on moving away from the Clojure Collector, I don't see us committing R&D time into this.

http://discourse.snowplowanalytics.com/t/replacing-the-clojure-collector/881
