### ISSUE TITLE
Scala Hadoop Shred: stray null in Postgres Constraints?

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2395]
https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-hadoop-shred/src/main/scala/com.snowplowanalytics.snowplow.enrich/hadoop/PostgresConstraints.scala#L73

vs this line:

https://github.com/snowplow/snowplow/blob/master/4-storage/postgres-storage/sql/atomic-def.sql#L86

and this line:

https://github.com/snowplow/snowplow/blob/master/4-storage/redshift-storage/sql/atomic-def.sql#L88

**Comment by fblundun** [comment]
I think this was intentional. There are actually 3 additional null entries in that PostgresConstraints list. They correspond to unstruct_event, contexts, and derived_contexts. They are there because the truncation happens before the deletion of those fields from the TSV ([here](https://github.com/snowplow/snowplow/blob/2001aef473215d3422b5a9ae61537b1c4b94465e/3-enrich/scala-hadoop-shred/src/main/scala/com.snowplowanalytics.snowplow.enrich/hadoop/ShredJob.scala#L138-L148)).

**Comment by alexanderdean** [comment]
Thanks for clarifying @fblundun - closing...
