### ISSUE TITLE
Scala Collector: network_userid issue

### ISSUE THREAD

**Issue by jramos** [snowplow/snowplow#2413]
I've noticed that in certain browsers, undoubtedly those which block 3rd party cookies, the `network_userid` will always be present in the collected event, but the value will change with every request from the user. My understanding was that if the `network_userid` cookie couldn't be set, no value would be recorded. Is this a bug in the Scala collector, or am I just misunderstanding?

**Comment by fblundun** [comment]
Hi @jramos ,

It's an interesting point. This is the intended behaviour. The Clojure Collector behaves the same way. The problem is that the collector has no reliable way of knowing whether the browser will accept or block the cookie. So we might as well always set the cookie in the hope that it is accepted.

I hope that makes sense!

**Comment by jramos** [comment]
:+1:

**Comment by alexanderdean** [comment]
The alternative would be to store the `network_userid` on read from the request (rather than logging on the initial response), but then we would only get the network_userid from the second event, not the first...
