### ISSUE TITLE
Scala Common Enrich: fix exception on same currency conversion

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2437]
```
Unexpected exception converting currency: [java.lang.IllegalArgumentException: Cannot convert to the same currency]"
```

The exception may originate [here](https://github.com/JodaOrg/joda-money/blob/250ef88e5f1ba84b0f724c29eb3a7bf861ad9337/src/main/java/org/joda/money/BigMoney.java#L1540)

**Comment by yalisassoon** [comment]
I've investigated this and it appears that any transactions in the base currency fail enrichment (and hence don't make it into the good rows) because the enrichment fails with the above error message.

This is really bad bug, because it means a large % of transactions (which are very high value events) fail to be processed successfully.

**Comment by alexanderdean** [comment]
Hey @chuwy - could you take a look at this one please ASAP? If you can get a fix into R77 (branch r77-rebase) that would be awesome.

**Comment by chuwy** [comment]
Sure, I'll have a look.

**Comment by alexanderdean** [comment]
Changed ticket name to match commit message

**Comment by chuwy** [comment]
This is not the case anymore in joda-money 0.11: https://github.com/JodaOrg/joda-money/issues/63
May be if for some reason OER give us wrong rate, exception here can be desirable?

**Comment by alexanderdean** [comment]
Ah, good to know
