### ISSUE TITLE
Bad rows should be one line of data per event

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#2438]
Currently, if a user is batching events so there are e.g. 5 events per POST requests, and one of those events fails validation, then it looks like all 5 events are stored in a single bad row, even if 4 out of 5 of those events was successfully processed.

If this is the case, it's going to make reprocessing the bad rows tricky, because there's a risk the 4 successfully processed events will be double loaded. (This wont happen if deduplication is setup, but will happen otherwise.)  

Is there a way that we can return just a single event? Or is that risky? (Because it means processing a raw bad row rather than logging it as is.) If so - we may just be better double processing and relying on the dedupe step to prevent the doubly processed data making it through.

**Comment by alexanderdean** [comment]
Yes - the behaviour is as you observed: when building each bad row, we link it back to the source `line` which produced the bad row, and that `line` could contain multiple source rows (not all of which are bad).

The way around this would probably to have an intermediate form of the event, and this intermediate form would be stored alongside the errors, rather than the source `line`.

It would be a lot of work to fix this behaviour, but it would make sense to do it when we refactor the pipeline to emit bad rows as well-structured Snowplow events rather than as a separate pipe of JSONs...

**Comment by alexanderdean** [comment]
I am treating this as a data loss issue, because this design decision (report the full collector payload for each event in that payload which fails) can cause OutOfMemory issues which blow up at least the batch pipeline:

* If you have POSTs of 100 events, and 50% of the events are bad, then
* Snowplow will try to write out 50 rows to bad, with each of the 50 rows containing the POST of 100 events
* This massive multiplicative effect causes OutOfMemory issues

When we get these OOMs, our only options are:

* Fail forwards, effectively discarding the problematic batches (data loss)
* If we are lucky, patch the offending schema (if there is one), bringing error rates down to a manageable rate
* Write a one-off clean up job in Spark to fix the underlying problem(s)

Treating this ticket as data loss given the first scenario is relatively common.

**Comment by alexanderdean** [comment]
This is important but can't be fixed in this milestone - it's a bigger topic.

**Comment by benjben** [comment]
Handled by #4106 

If a failure happens while extracting the events from a collector payload (containing several events), none of the events will be enriched (as before). But if the events can be successfully extracted, then an enrichment failure for one of this event will contain only this event, while the others can be successfully enriched (new).
