### ISSUE TITLE
Documentation refers to out of date concept "macros"

### ISSUE THREAD

**Issue by 0xABAB** [snowplow/snowplow#2520]
In the documentation "Integrating javascript tags with Google Tag Manager" it refers to "macros" and various out of date screenshots. 

Macros as such do not exist anymore in Google Tag Manager. 

Suggested solution: new screenshots + rewrite text.

**Comment by ezefranca** [comment]
https://github.com/contact?report=0xABAB

**Comment by ihortom** [comment]
@alexanderdean - Updated the larger half of the doc. The new version of GTM is quite different. It's time consuming to update all the screenshots and instructions due to the sheer size of the article and the fact I have never used GTM before. You can either push what I currently modified or wait till I complete the whole page.

**Comment by alexanderdean** [comment]
Thanks - let's wait!

**Comment by ihortom** [comment]
@alexanderdean - please, review and push (can be closed).

**Comment by alexanderdean** [comment]
Hi @ihortom - which pages are updated for this ticket?

**Comment by ihortom** [comment]
@alexanderdean - https://github.com/snowplow/snowplow/wiki/Integrating%20javascript%20tags%20with%20Google%20Tag%20Manager. Are there any more? The local copy is [here](https://github.com/ihortom/snowplow-wiki-temp/wiki/Integrating%20javascript%20tags%20with%20Google%20Tag%20Manager).

**Comment by alexanderdean** [comment]
Thanks @ihortom - the best people to review this are @yalisassoon and @fblundun - assigning to Yali to review. I can push once finalized.

**Comment by ihortom** [comment]
@yalisassoon - could you, please, review the page. There are so many in the "backlog" because of this waiting to be pushed. The local copy I created is [here](https://github.com/ihortom/snowplow-wiki-temp/wiki/Integrating-javascript-tags-with-Google-Tag-Manager).

Note the last screenshot (preview) does not reflect the actual scenario discussed on the page but it is the representation of the current Google look. Thus if you do have (or can produce) that screenshot for  the actual scenario, please, share.

/cc @alexanderdean / @fblundun

**Comment by fblundun** [comment]
`"//://{{SUBDOMAIN}}.cloudfront.net/sp.js.cloudfront.net/2.6.0/sp.js"`

should be

`"//{{SUBDOMAIN}}.cloudfront.net/sp.js.cloudfront.net/2.6.0/sp.js"`

Other than that it looks good to me...

**Comment by ihortom** [comment]
@fblundun - thanks for spotting this. Corrected.

**Comment by yalisassoon** [comment]
Looks great @ihortom! I've added a screenshot here: `setup-guide/images/gtm-debug.png` @alexanderdean please merge.

**Comment by alexanderdean** [comment]
Merged!

**Comment by ihortom** [comment]
@alexanderdean - updated the last screenshot (kindly provided by @yalisassoon)

**Comment by alexanderdean** [comment]
Re-pushed
