### ISSUE TITLE
EmrEtlRunner: placeholder for "Factotum inside"

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2577]
The EmrEtlRunner's DAG runs inside of EMR as a jobflow. If EmrEtlRunner is run by Factotum, it is not currently possible for Factotum to "see inside" EmrEtlRunner to understand which jobflow step in EMR is currently being run.

It would be nice if the EmrEtlRunner while running had some easy way for the parent Factotum process to find out what the status of the inner DAG is:

```
Factotum   ~query->   EmrEtlRunner     ~query->   EMR
          <-return~   jobflow status  <-return~
```

/cc @ninjabear, @yalisassoon

**Comment by ninjabear** [comment]
I completely understand the need here - and this is how tools like Azkaban work. Each job can report back to the job runner, and that "snapshot" of where the job is being stored in a database like mysql. However, I think we should go about this in a different way for the following reasons:

1. The task calling back to the job runner introduces a two way dependency - right now we have the control path flowing from Factotum to EmrEtlRunner. So if we change Factotum, EmrEtlRunner has no idea, and it doesn't actually need to know. Adding this in would mean EmrEtlRunner is coupled to some version of Factotum, and it also means we give any other vendor the ability to chain themselves to a version of Factotum. In order to keep factotum iterating without getting "stuck" with this kind of thing (ie. if I touch X then I have to edit X,Y,Z and persuade xyz to adopt my changes) we need to be quite strict about this control path 

2. It'd very likely introduce external dependencies (or anchor us to an operating system). If you really want to push on with this the way I'd probably go about it is to have EmrEtlRunner expose a "debug port" where it writes it's current state. That gets us around having to have a database, or using something like pipes. Using files is obviously possible too, but files are kind of error prone because of how the operating system works - flushing, caching etc. Doing it this way still doesn't give us a reliable (schema'd?) way to give this information out to snowbot (or others) either.

### So my suggestion is..

We make it possible to run EmrEtlRunner steps/tasks using Factotum directly - ie introduce options into EmrEtlRunner to run a single step only, and export the "dag" side to Factotum. I think we should do it this way because:

1) avoids problems above
2) provides a path to maintain and or rewrite EmrEtlRunner in parts
3) individual task logs and status (including stdin/out/err) will be fed back into Factotum for free (and in later versions of Factotum, the task results will very likely be available realtime as schema'd json)

The catch is this - the granularity of feedback will be limited by how small we can make tasks in EmrEtlRunner.

What's your thoughts on this?

**Comment by alexanderdean** [comment]
Hey @ninjabear - I agree with everything you've said and this is 100% how I'd like the SQL Runner integration to work: essentially you have a CLI argument on SQL Runner to spit out the playbook as a Factotum DAG which can then be composed into the parent Factotum DAG. The SQL Runner is then delegated to run each individual step one by one (in other words, a playbook with 20 SQL scripts will translate to 20 individual SQL Runner invocations).

With EmrEtlRunner, I had thought this wasn't going to be possible because the EMR portion of the DAG is stateful - i.e. all of the EMR steps have to be run on the same cluster in sequence. So running individual steps isn't going to work.

**However**, thinking about it some more, I think your above approach can work - the trick is that we need to bring forward #936, and think of it a 5-step EMR job flow as 5 EmrEtlRunner invocations *on an existing cluster*. That removes the stateful-ness requirement.

Exciting!

**Comment by ninjabear** [comment]
Awesome! One way to do it (in the spirit of #936) is to think of EmrEtlRunner more as service, so the pseudo steps are:

1. EmrEtlRunner up
    * any stateful setup
2. exec step abc
3. exec step xyz
...
4. EmrEtlRunner down 

This can be accomplished pretty transparently to the user by having a pid file and the first invocation triggering the "EmrEtlRunner up" step and subsequent calls checking if an existing "service" for that cluster is available. The service times out after a while, or if a job on a different cluster is specified (the "EmrEtlRunner down" step).  This is [how gradle works](https://docs.gradle.org/current/userguide/gradle_daemon.html). The downside is it's a bit of a fiddle coding it, however it's a pattern that will always work with Factotum (and any other tool).

**Comment by alexanderdean** [comment]
This is an interesting idea - remember though that we have N independent instances of EmrEtlRunner running at any time on a given server...

**Comment by ninjabear** [comment]
Sure - perhaps "service" isn't a great analogy from me, since it implies a "global" daemon. I'm thinking if you put the pid in the working directory, or with the configuration, only subsequent runs from that location would link to that process. 

If we can remove the stateful requirement using some parameters, I think that'd be preferable! I'm just trying to say that we'll never get snookered by pulling DAGs out of applications and into Factotum - even if they are stateful.

**Comment by alexanderdean** [comment]
Makes sense @ninjabear - I really like your syntax too:

```
emr-etl-runner batch up
emr-etl-runner run "first step"
emr-etl-runner run "second step"
emr-etl-runner halt
```

**Comment by alexanderdean** [comment]
Closing but this design lives on https://github.com/snowplow/dataflow-runner
