### ISSUE TITLE
Add CI/CD for Kinesis apps

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2621]
Initially, this will just cover the Scala Stream Collector, Stream Enrich, and Kinesis Elasticsearch Sink.

The two possible approaches were:

1. Always deploy any commit to the "develop" branch
2. Always deploy commits tagged in a specific way

The first option is problematic when people working on two different subprojects (e.g. stream enrich and hadoop shred) want to simultaneously use the continuous deployment - more than one CI/CD branch would be required.

For the second option, we thought we would start off using simple tag names like "r80-rc2". Possible extensions to this:

* Add an explicit prefix to tags intended for deployment, e.g. "cicd:r80-rc2"
* Include in the tag a list of which subprojects to deploy and in what order, e.g. "r80-rc2:sce;she,shs" to publish Scala Common Enrich, then both Scala Hadoop Enrich and Scala Hadoop Shred.

We also thought that it should be the responsibility of the committer (rather than the continuous deployment) to ensure that the versions in the BuildSettings files are correct.

**Comment by alexanderdean** [comment]
Thanks both - this is coming along nicely. I agree that tag names are the way to go. I agree that it should be the committer's responsibility to ensure `BuildSettings` versions are correct.

The two extensions around the tags are interesting. I was pondering an alternative approach, where the CI/CD can figure out what needs to be pushed. I guess it would have to compare versions in `BuildSetttings` with what is available on Bintray. This means that the CI/CD needs some "business understanding" of this repo's artifacts, but I don't think that's avoidable in snowplow/snowplow due to the complexity of the layout (and the various release scenarios we need to support).

Thoughts?

**Comment by ninjabear** [comment]
@alexanderdean we can have some logic that establishes what needs building, using `git diff --name-only` or similar in the corresponding directories (so if something has changed under say, the EmrEtlRunner directory then we need to rebuild and repush that). 

I think we'd be starting to work against the grain though, traditionally one repository compiles to one artifact, even if that artifact is composed of N other artifacts - e.g. "snowplow rXX is clojure-collector 0.1.0, stream-collector 0.2.0..". 

With custom crafted tags we're trying to give a tag a scope - but tags are a bookmark to a position in the whole repository. We're saying that everything in this repository at this point in time works together - this is the same paradigm that travis follows for better or worse.

For the example we're currently looking to implement, we'd push the tag r80-rc1, but would have bumped the kinesis version inside that - "this is a candidate release of snowplow r80 - it uses a new kinesis elasticsearch sink". Do you think this kind of system could work for us?

**Comment by alexanderdean** [comment]
Hey @ninjabear - lots of good points there.

> I think we'd be starting to work against the grain though, traditionally one repository compiles to one artifact, even if that artifact is composed of N other artifacts - e.g. "snowplow rXX is clojure-collector 0.1.0, stream-collector 0.2.0..". 

This has never really been the direction of travel in `snowplow/snowplow` - instead it consists of more and more individual apps and libraries (Scala Hadoop Enrich, Scala Common Enrich, Stream Enrich etc) which are independent (though possibly with cross dependencies in the case of Scala Common Enrich), published as standalone artifacts and orchestrated by separate technology (EmrEtlRunner; Tupilak).

If we accept that direction of travel, then the challenge for CI/CD has to be how to decide what artifacts to publish at a given point in time. The CHANGELOG shows how different releases will only ever update a subset of artifacts:

https://github.com/snowplow/snowplow/blob/master/CHANGELOG

I think there are only two strategies here:

1. We use git tag "hinting" to express the artifacts which are required
2. We ask the CI/CD to perform an "artifact diff" to determine what needs pushing

I think both options have merit. My concern with option 1 is that it introduces the possibility for human error - for example, somebody performing the final merge to master forgets to tag hint that common enrich needs to be published before Scala Hadoop Enrich is re-assembled.

The idea of CI/CD determining what needs pushing and in what order - I agree it's more intelligence than you would normally see in a CI/CD process, but Snowplow is a complex project so that logic is always going to have to live somewhere, regardless of repo layout. I think having that logic crystallized in a build process has some merit.

Thoughts please!

**Comment by ninjabear** [comment]
@alexanderdean It's not going to be a big problem if we keep the "loose collection of artifacts" direction of travel - however if we could split the repo into the collection of artifacts that we do update together (real-time/batch?) it would give us a couple of advantages downstream;

* At some point, any number of engineers will try to "download" snowplow and get a bit confused about what bits they need. We can simplify that for them - especially if we include a install guide for the default setup inside the zip
* When we're trying to upgrade a client to the latest version of snowplow we could download a single zip (product-version) which would include any migration scripts - the versions are guaranteed to run together (no need to check them again)

I think if we don't split the project up with submodules (or other) then we should dig in and start a build script inside the snowplow/snowplow repo.

I think this because if we have some non-standard build logic we need to capture it as neatly as possible, and keep it outside the build tool where we can. This means we'll remain fairly build tool agnostic, and we'll never lose the ability to build our product (surprisingly this does happen).

Python is often used in this capacity - realistically we have a choice between python or ruby (using rake would be nice since build tools understand it). (We could also feasibly use gradle and a fair chunk of groovy - this has the advantage of having a bintray plugin provided by bintray). I'd like to avoid bash as much as possible since we can provision any interpreter we need and still provide the ability to build it yourself locally in vagrant.

So - looping back to your comments on hinting or automatically, if we write a custom build script we'll probably have both - the step to see if the artifacts have changed will be a validation step (we want to keep the tags and the releases married). This would prevent you from deploying anything that didn't have both parts (a tag, and changes).

I think the way to look at the process deploying with crafted tags is, not that it's a button to deploy a release - but that the tag defines the release. Consider it from a support point of view - customer reports problem, they're using 0.1.0 of xyz - I need to check out that version in order to replicate the problem (you could download the artifact - but the source code is invaluable in figuring out the fix). If the tags are confusing, or have been deleted it makes things more difficult than it need be. We can also add multiple tags to the same commit, each will trigger a deploy, so we don't need the capacity to specify multiple releases in the same tag (I don't think?).

**Comment by alexanderdean** [comment]
Hey @ninjabear -

> however if we could split the repo into the collection of artifacts that we do update together (real-time/batch?) it would give us a couple of advantages downstream

We already have this with the Kinesis pipeline (`push kinesis` publishes a zipfile containing three separate stream processing apps) - but in fact users want us to move away from this because they prefer to interact with our individual binaries through an intermediary like DockerHub:

* https://github.com/snowplow/snowplow/issues/2493
* https://github.com/snowplow/snowplow/issues/1707

Tupilak will ultimately promote this pattern too.

Similarly, with the Hadoop pipeline there's no user demand to download a zipfile which contains all of our Hadoop jars - instead we publish these jars to S3 (`s3://snowplow-hosted-assets`) and EmrEtlRunner mediates use of these.

Another way to think of it is that any given release of Snowplowis a bit like a Linux distribution: it's a rubber-stamped version of Snowplow where everything is guaranteed to work together; unlike a Linux dist however, a Snowplow release isn't shipped in a monolithic zipfile - instead there are configuration files like `config.yml` which assert the new versions to use.

(So why is Snowplow shipped from a single repository? Because it would be incredibly difficult to hold the whole system in your head for a new release if it fragmented into 20-30 repos with cross-dependencies.)

> I think if we don't split the project up with submodules (or other) then we should dig in and start a build script inside the snowplow/snowplow repo.
> 
> I think this because if we have some non-standard build logic we need to capture it as neatly as possible, and keep it outside the build tool where we can. This means we'll remain fairly build tool agnostic, and we'll never lose the ability to build our product (surprisingly this does happen).

All sounds good!

> Python is often used in this capacity - realistically we have a choice between python or ruby (using rake would be nice since build tools understand it). (We could also feasibly use gradle and a fair chunk of groovy - this has the advantage of having a bintray plugin provided by bintray). I'd like to avoid bash

Agree re bash. I am not a huge fan of Groovy so would lean towards Ruby with Rake.

I am a bit hazy on your last two paragraphs Ed:

> I think the way to look at the process deploying with crafted tags is, not that it's a button to deploy a release - but that the tag defines the release

But the example was `r80-rc2:sce;she,shs` - that only describes the release as a delta from R79; it doesn't describe the release of the "Snowplow distro" in its entirety (unlike e.g. our Version matrix spreadsheet).

> Consider it from a support point of view - customer reports problem, they're using 0.1.0 of xyz - I need to check out that version in order to replicate the problem (you could download the artifact - but the source code is invaluable in figuring out the fix)

It's a bit fiddly, but at the moment you would just look up the version in the Version matrix spreadsheet and check out a Snowplow release containing 0.1.0 of xyz. Can that be replicated in a human-friendly tag?

(A thought: in due course, I think it could be interesting to update the Version matrix as part of the CD process. This would give you a simple cross-check that all of the expected artifacts have been deployed...)

My gut feel is that we should move quickly to a probably-Ruby build script in snowplow/snowplow which:

1. Has an understanding of all the potential artifacts (binaries; libraries) currently available within snowplow/snowplow
2. Understands the dependency graph between artifacts - e.g. Common Enrich should be published before Hadoop Enrich or Stream Enrich
3. Can automatically publish any artifacts which have an updated git history

For now I think we should stick to simple tags (`r80`, `r80-rc1`)...

**Comment by ninjabear** [comment]
Sorry I didn't explain that well at all -

    I think the way to look at the process deploying with crafted tags is, not that it's a button to deploy a
    release - but that the tag defines the release

What I mean by this is, if we had the history on the left:

![explain](https://cloud.githubusercontent.com/assets/5323141/14892336/44c8da16-0d62-11e6-953c-2f15819aeb40.png)

We have the ability to single out specific releases of individual components. So there's some logic - just using git tag - that can tell us what's in a specific release. We can also then use tags to tell what the latest release of a specific component is, and what versions are in each "r80" style release. 

    Consider it from a support point of view - customer reports problem, they're using 0.1.0 of xyz - I
    need to check out that version in order to replicate the problem (you could download the artifact - 
    but the source code is invaluable in figuring out the fix)

So now - If I know the release, I can just check out r80 (and the versions of things will be correct) or if I  can see that they're using common-enrich 0.1.0 I can check out common-enrich/0.1.0.

Directly translating my ramble on "tag buttons" I mean that a tag is a release, we should make it as expressive as possible, and a 1:1 mapping with an artifact if we can. 

I don't think there's a real action from what I'm saying here - other than it's possible, and it may simplify working with the repository - and get us nearly all the way to representing the version matrix in source control. We should keep it simple for now!

**Comment by alexanderdean** [comment]
Hey @ninjabear - thanks for taking the time to explain that. I think the approach on the LHS is great - it would give us a much more useful tag history, and yes it would effectively drive our version matrix, which is really neat...

I guess the open question is whether we go:

```
human -> tagging -> build script cross-check
```

or:

```
build script -> tagging
```

**Comment by ninjabear** [comment]
@alexanderdean I'd go with the second option if possible. So we'd need to push a tag, like "r80" to get things started, then the build script can automatically establish what's changed, and what the versions now are (and push the corresponding tags back to the repo). 

There is one catch with that though, and that is that we'd still need a way to bake in what should be in a release. So if it common-enrich has changed, we'll get that from the history - but many other things make up a release and they may not all have changes - but should still be "reissued" under the new release. Obviously this can change for different types of releases.

**Comment by alexanderdean** [comment]
Hey @ninjabear - I agree, I much prefer option 2.

> So we'd need to push a tag, like "r80" to get things started, then the build script can automatically establish what's changed, and what the versions now are (and push the corresponding tags back to the repo). 

Yep.

> There is one catch with that though, and that is that we'd still need a way to bake in what should be in a release.

Yes - we will need a bit of a dependency tree in our build script. So push Common Enrich before Hadoop Enrich, for example.

> many other things make up a release and they may not all have changes - they should still be "reissued" under the new release. 

How do you define re-issuing in this context?

**Comment by ninjabear** [comment]
If I change hadoop-shred, I could do it without upgrading common-enrich - would we want both to appear in the resulting release zip? If so then common-enrich would be "reissued" as part of the new release since it hasn't changed.

**Comment by alexanderdean** [comment]
That specific example doesn't quite flow because Hadoop Enrich would be pushed to S3 and Common Enrich would be pushed to Maven, and we should treat deployed artifacts as immutable. But I know what you mean: if a release changes Stream Collector and Stream Enrich but not Elasticsearch Kinesis Sink, then yes currently our all-kinesis-apps-zip would need to include the last previous Elasticsearch Kinesis Sink too...
