### ISSUE TITLE
Make it clear in the documentation that multiple contexts of the same type can be sent with a single event

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#2622]
This is something we're asked quite a lot - see e.g. http://discourse.snowplowanalytics.com/t/multiple-contexts-of-the-same-type/161

**Comment by ihortom** [comment]
@yalisassoon / @alexanderdean - Updated 2 pages (locally):

- [Contexts overview](https://github.com/ihortom/snowplow-wiki-temp/wiki/Contexts-overview)
- [2-Specific-event-tracking-with-the-Javascript-tracker#315-custom-contexts](https://github.com/ihortom/snowplow-wiki-temp/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#315-custom-contexts)

Let me know if you think of any other pages. Otherwise push and close.

**Comment by alexanderdean** [comment]
Thanks pushed!
