### ISSUE TITLE
scala-stream-collector should set X-Forwarded-For to user.ipAddress

### ISSUE THREAD

**Issue by liningalex** [snowplow/snowplow#2642]
in scala-stream-collector current code, it's wrongly set proxy or load balancer ip address to user.ipAddress. Instead, it should grab it in http header - X-Forwarded-For that is the originating IP address of a client connecting to a web server through an HTTP proxy or load balancer.

**Comment by fblundun** [comment]
Hi @liningalex , we actually fix this in the enrichment step instead of in the collector. Scala Common Enrich has access to the headers for the event and will use the X-Forwarded-For header (if it exists) as the IP address. The relevant ticket is [here](https://github.com/snowplow/snowplow/issues/1372). Closing since I believe that makes this ticket unnecessary.
