### ISSUE TITLE
Placeholder for selecting a Kafka-to-S3 archiver for use with Snowplow

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2656]
- Secor?
- Bifrost?
- Kafka Connect?

Would be a shame to have to implement something from scratch, or to have to extend our [kinesis-s3](https://github.com/snowplow/kinesis-s3) to support Kafka...

**Comment by simplesteph** [comment]
Kafka-Connect for sure, has a hard dependency on integrating with the schema registry, see http://discourse.snowplowanalytics.com/t/discussion-improvement-kafka-optionally-support-avro-and-the-schema-registry/1127

**Comment by alexanderdean** [comment]
@simplesteph where is the standard format for writing Confluent Schema Registry-compatible records defined? Having trouble finding it...

**Comment by simplesteph** [comment]
It's avro. The process is as such.

Define your avro schema (optionally register it on your schema registry, although the code should do it for you).
Serialize your data using this avro schema
Write to Kafka using the AvroSerializer (see serializer here: http://docs.confluent.io/3.2.0/schema-registry/docs/serializer-formatter.html#serializer)

The link here basically shows you how to write avro data in java: http://docs.confluent.io/3.2.0/schema-registry/docs/serializer-formatter.html#serializer

More doc here: http://docs.confluent.io/3.2.0/schema-registry/docs/intro.html#quickstart

**Comment by alexanderdean** [comment]
If it's vanilla Avro, then how is the Avro record associated with an entry in the Confluent Schema Registry?

**Comment by simplesteph** [comment]
@alexanderdean sound counter intuitive right? :)
Let's have a deeper look at:
http://docs.confluent.io/3.2.0/schema-registry/docs/serializer-formatter.html#serializer

```
Properties props = new Properties();
props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG,
          io.confluent.kafka.serializers.KafkaAvroSerializer.class);
props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG,
          io.confluent.kafka.serializers.KafkaAvroSerializer.class);
props.put("schema.registry.url", "http://localhost:8081");
```

As you can see, the serializer isn't just any Avro serializer, it's `io.confluent.kafka.serializers.KafkaAvroSerializer.class`. Now you can look at the implementation herehttps://github.com/confluentinc/schema-registry/blob/master/avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroSerializer.java, but what it needs is the `schema.registry.url`, see https://github.com/confluentinc/schema-registry/blob/master/avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDeConfig.java#L33

What this serializer does is split the schema from your avro record, stores the schema in the schema registry (that's why you need to provide a url), and then stores the avro record in Kafka. Basically your record is split between Kafka and the schema registry. A consumer needs to use a special deserializer (provided by Confluent again) to retrieve the schema from the registry and add it to the avro record it receives. 

Does that help?

**Comment by alexanderdean** [comment]
Yech, this sounds incredibly opaque.

> Basically your record is split between Kafka and the schema registry

So I am attempting to write `Avro[foo]` to a Kafka topic. What *precisely* is stored in my Kafka record - and where is that documented?

**Comment by simplesteph** [comment]
@alexanderdean you should try it out to get more comfortable with it, okay? :)
The documentation of what's stored in Kafka is here: http://docs.confluent.io/3.2.0/schema-registry/docs/serializer-formatter.html#wire-format 

```
The wire format currently has only a couple of components:

Bytes	Area	Description
0	Magic Byte	Confluent serialization format version number; currently always 0.
1-4	Schema ID	4-byte schema ID as returned by the Schema Registry
5-...	Data	Avro serialized data in Avro’s binary encoding. The only exception is raw bytes, which will be written directly without any special Avro encoding.
Note that all components are encoded with big-endian ordering, i.e. standard network byte order.
```

**Comment by alexanderdean** [comment]
Thanks, I'll feed this back into the Discourse post...
