### ISSUE TITLE
Add versioned pages to Scala Tracker technical documentation

### ISSUE THREAD

**Issue by 0xABAB** [snowplow/snowplow#2660]
Title was:    subject.setUseragent("A") documented, but not implemented in scala tracker 

   subject.setUseragent("A") documented, but not implemented in scala tracker.

**Comment by chuwy** [comment]
This will be fixed in https://github.com/snowplow/snowplow-scala-tracker/issues/34.

**Comment by alexanderdean** [comment]
The underlying problem here is that the documentation for the Scala Tracker is not being versioned. @chuwy - please implement versioning for the documentation. Please see how e.g. the Android Tracker handles versioning. We should have versions 0.1.0, 0.2.0 and "latest" (0.3.0), with a warning on 0.3.0 that it is pre-release.

**Comment by chuwy** [comment]
Done!

**Comment by alexanderdean** [comment]
Thanks!
