### ISSUE TITLE
Rename user_id in the client session context

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow#2696]
A common question in our support forums: What's the difference between `user_id` in `atomic.events` and `user_id` in the client session context?

I'd consider renaming the second `user_id` to something that better captures what it is – perhaps `install_id`?

**Comment by alexanderdean** [comment]
We need to get Snowplow users comfortable with the idea that there are multiple possible user identifiers for the event, just like there are multiple event timestamps:

* The `user_id` in `atomic.events` is essentially a business-owned identifier for the user. Over time this will move out into a dedicated context (as will everything in `atomic.events`) and the tracker `setUserId()` methods can become sugar around https://github.com/snowplow/snowplow-javascript-tracker/issues/405
* The `user_id` in the client session context is typically used as a synthetic (tracker or collector-created) proxy ID for the user, with this proxy user ID being held in some kind of storage (maybe cookie or SQLite or similar) so that it (mostly) survives across sessions

**Comment by bogaert** [comment]
I understand the difference, but we wouldn't rename `domain_userid` to `user_id` if we were to move it to a context. These are all possible user identifiers, just like the IP address and user fingerprint.

Most users will look at what the field is called, rather than look at the documentation (which can be hard to find). We should therefore make the field names as descriptive as possible, in my opinion.

**Comment by alexanderdean** [comment]
`domain_userid` will move out into an instance of the `client_session` context in due course. We can definitely do a breaking 2-0-0 of the `client_session` with the `user_id` property renamed - open to suggestions for a better name...

**Comment by bogaert** [comment]
I'd do the breaking change. It's a small thing, but something I have had to explain each time the client session context has come up. A good time to do the change might be to do it when we move `domain_userid` into the `client_session` context (and most users will have to update their queries).

A couple of ideas:

- `install_userid` (perhaps too specific to iOS and Android)
- `tracker_userid`
- `snowplow_userid`

**Comment by alexanderdean** [comment]
Sounds good. A couple more options:

* `client_userid`
* `client_id`

**Comment by teffi** [comment]
Are there any plans on pushing this through? I'm currently integrating the iOS SDK and got confused also. Better if we could mention this and reference the discourse thread on the official docs.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/92
