### ISSUE TITLE
Common: add continuous deployment for Scala Common Enrich

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2702]
We could set this up so you do this by pushing two tags: one to deploy SCE and one to deploy RT (real-time). But then there's a bit of a race condition - the build for the second tag can fail because the build for the first tag hasn't made the latest SCE version available fast enough. So maybe we just manually wait between pushing the SCE tag and pushing the RT tag?

**Comment by alexanderdean** [comment]
We need a tag syntax that supports expressing both right? Because they have
to be the same code commit, because they have an inter-dependency...

On 3 Jun 2016 2:33 p.m., "Fred Blundun" <notifications@github.com> wrote:

>

> We could set this up so you do this by pushing two tags: one to deploy
SCE and one to deploy RT (real-time). But then there's a bit of a race
condition - the build for the second tag can fail because the build for the
first tag hasn't made the latest SCE version available fast enough. So
maybe we just manually wait between pushing the SCE tag and pushing the RT
tag?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
<https://github.com/snowplow/snowplow/issues/2702>, or mute the thread
<https://github.com/notifications/unsubscribe/AAMPP5A9YaPzR2Pi9Wcuc2bPLf-bW1VMks5qIC0NgaJpZM4ItiPI>
.

**Comment by BenFradet** [comment]
done in #3216
