### ISSUE TITLE
New JSON Path file, SQL table definition and migration script for com.snowplowanlaytics.snowplow geolocation_context 1-1-0

### ISSUE THREAD

**Issue by kingo55** [snowplow/snowplow#2864]
I noticed the new 1-1-0 schema includes the timestamp from the geo location API. However we don't have a migration script, table def or JSON path file to make use of it in Redshift. Currently just:

**JSON Schema**
https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/geolocation_context/jsonschema/1-1-0

**JSON path**
https://github.com/snowplow/snowplow/blob/master/4-storage/redshift-storage/jsonpaths/com.snowplowanalytics.snowplow/geolocation_context_1.json

**Table definition**
https://github.com/snowplow/snowplow/blob/master/4-storage/redshift-storage/sql/com.snowplowanalytics.snowplow/geolocation_context_1.sql

Would you guys be open to a pull request for 1-1-0 files? We've started collecting fine locations as part of a split test and will be writing these ourselves anyway.

**Comment by alexanderdean** [comment]
Hey @kingo55 - we can't unfortunately merge a PR for this right now. The reason is that in the current architecture, all Snowplow installations are using the same hosted JSON Paths file, and we can't unilaterally change that file (adding a column) without breaking people's existing Redshift loads. @chuwy is soon going to start on a full rewrite of the StorageLoader to start resolving this problem, but until this is done, we are unfortunately stuck on the 1-0-0 schemas everywhere...

You're of course welcome to use the newer 1-1-0 in your own installation, and I'll keep this ticket in the [Blocked schemas](https://github.com/snowplow/snowplow/milestone/79) milestone so that people are aware of the gap...

**Comment by kingo55** [comment]
Ah of course. No worries @alexanderdean ...

**Comment by alexanderdean** [comment]
Migrated to https://github.com/snowplow/iglu-central/issues/519
