### ISSUE TITLE
Placeholder for supporting redirect URLs and other parameters containing non-escaped characters

### ISSUE THREAD

**Issue by bernardosrulzon** [snowplow/snowplow#2913]
Hey @alexanderdean!

We've just implemented a redirect to our AdWords campaigns to allow us to compare AdWords clicks vs. actual visits to the site. The thing is we're using a ValueTrack parameter `{keyword}` which passes the keyword that was, **and may have spaces**.

Google sends a request to the following URL: `https://analytics.getninjas.com.br/r/tp2?u=https://www.getninjas.com.br/orcamentos/aulas/idiomas/espanhol%3Futm_source%3DGoogleSearch%26utm_medium%3Dcpc%26utm_campaign%3D596332072%26utm_term%3Db-%2Bprofessor%20%2Bespanhol%26utm_content%3D149092461776%26matchtype%3Db%26device%3Dc%26device_model%3D&gclid=CLm_59Xr188CFReBkQodGzwPMQ`

(note that spaces are correctly encoded as `%20`)

Snowplow redirects users to the following URL: `https://www.getninjas.com.br/orcamentos/aulas/idiomas/espanhol?utm_source=GoogleSearch&utm_medium=cpc&utm_campaign=596332072&utm_term=b-+professor +espanhol&utm_content=149092461776&matchtype=b&device=c&device_model=`

(note that Snowplow converted `%20` to actual space)

The uri_redirect event then fails validation, as it's not a valid URI

**Comment by bernardosrulzon** [comment]
A side question for the experts: Snowplow is attempting the redirect users to a URL with spaces, which AFAIK is not best practice - any chances this breaks something for end users?

**Comment by alexanderdean** [comment]
Hey @bernardosrulzon - the underlying problem is that the original `&u=...` value is not correctly URL encoded. If it were URL encoded, then e.g. `http:` would be `http%3A%2F%2F`, and `utm_term%3Db-%2Bprofessor%20%2Bespanhol` would be `utm_term%253Db-%252Bprofessor%2520%252Bespanhol` (double encoded spaces).

Is there an option to correctly URI encode the `&u=` parameter?

**Comment by bernardosrulzon** [comment]
Good point. I think we can encode the first part of the URL `http://...`, but not the `{keyword}` variable, which may contain special characters.

**Comment by Rajadas** [comment]
My issue is similar but slightly different.

Some links we track need placeholders like this ##ASPID##, others like this %%ASPID%%. The exact placeholder tag %%ASPID%% will then be replaced by some values, if they exist, so encoding them is not an option.

The first case has no problem at all, **302 Redirect**, the second one gets stuck in the collector, **400 Bad Request**, without the expected redirection.

Take a look:

http://collector.snplow.com/r/tp2?u=https%3A%2F%2Fgithub.com%2Fsnowplow%3Faspid%3D##ASPID##

http://collector.snplow.com/r/tp2?u=https%3A%2F%2Fgithub.com%2Fsnowplow%3Faspid%3D%%ASPID%%

**Comment by alexanderdean** [comment]
Hi @Rajadas - I think it's the same issue? The `%%ASPID%%` case fails because `%` is part of the URI encoding. If you could flag that links containing `%%ASPID%%` should be treated as non-escaped, that should work?

**Comment by Rajadas** [comment]
Hey @alexanderdean if there's a way to flag that the content of u= parameter contains non-escaped characters, that could work.

**Comment by alexanderdean** [comment]
Yes, the idea is that we add a separate QS parameter called e.g. `neu` (non-escaped URI) which:

* **must** be the last parameter on the QS (because otherwise it's impossible to know where the URI ends)
* **must** be treated as a non-escaped URI

Does that make sense?

**Comment by Rajadas** [comment]
Sounds perfect 👍

**Comment by bernardosrulzon** [comment]
Sounds good to me!

**Comment by alexanderdean** [comment]
I have broadened the description of the ticket to include another scenario, where:

* Ad creatives need to go through an audit process before they go live
* In the audit process the creative is reviewed to ensure that the clickthrough works.
* A user has macros within the click url which are populated at auction time by the bidder
* During the audit process, since the bidder does not serve the creative, these macros will be left as is and so will be passed to the collector
* The collector returns a 400 due to [this code](https://github.com/snowplow/snowplow/blob/master/2-collectors/scala-stream-collector/src/main/scala/com.snowplowanalytics.snowplow.collectors/scalastream/ResponseHandler.scala#L197-L200)
* The audit process fails due to the 400 from the collector

This is a distinct scenario from the other one above, relating to unescaped macros *inside* the redirect URI.

**Comment by BenFradet** [comment]
links to #3880

**Comment by benjben** [comment]
Handled by #4003.
