### ISSUE TITLE
Clojure Collector: make Flash access domains and secure configurable

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2914]
Regarding:

https://github.com/snowplow/snowplow/blob/master/2-collectors/clojure-collector/java-servlet/src/snowplow/clojure_collector/responses.clj#L129

It would be nice to make this configurable so that a user can lock down their CORS to only their own domains, and secure true. The default should be no crossdomain file at all, and we should provide documentation on setting it to the user's specific domain `*.acme.com`.

**Comment by alexanderdean** [comment]
Confusingly I renamed the ticket, making it a dupe of #2915. Renaming it back.

**Comment by joho** [comment]
Hi there. Is there any plan/schedule on when this will get addressed? It's a blocker on some security work we'd like to do at work.

**Comment by BenFradet** [comment]
The priority has been given to the Scala Stream Collector in #2915 (for which the change is almost out the door) since the Clojure Collector is on its way out as per [our RFC](https://discourse.snowplowanalytics.com/t/replacing-the-clojure-collector/881).

I believe we'll get around to making this change to the Clojure Collector too, however the timeline is not clear at this time.

**Comment by alexanderdean** [comment]
Bringing forwards
