### ISSUE TITLE
Scala Common Enrich: geo-fencing enrichment

### ISSUE THREAD

**Issue by ironsideshu** [snowplow/snowplow#2917]
Hi @alexanderdean and Snowplow gang!

We are flirting with the idea of creating a geo-fencing enrichment and wanted to the gauge interest/usefulness of the idea. The main application for this would be for tracking mobile devices and it would be most useful in the streaming option (but depending on the use case, batch will have its uses). 

The concept is pretty straight forward, when an event is examined (or when an event comes in), geo-locate the event (into lat/long) if possible (via geo-location or IP lookup), and if the lat/long is available, search it against a set of boundaries and/or point proximities. The natural use of this is that you can flag a user going into a zone of interest, the time spent in the zone, and when the user leaves the zone. With these flags, we have several use cases where they are useful for understanding user behavior. The biggest piece that's missing currently is the service that stores the boundaries/point proximities of interest and allows searches against them. 

We currently have a pretty good plan on a REST API that allows the storage of the boundaries of interest and the search feature that is needed (and it's scalable to boot(!)), but we want to hear your thoughts (and whoever else that uses Snowplow(!)) about the usefulness of this enrichment before we go down the rabbit hole. Any comments/opinions would be appreciated!

**Comment by alexanderdean** [comment]
Hey @ironsideshu ! This is a really cool idea. We noodled around with something similar before - #997. The main difference I think I'm hearing here is that you want the geofence database to be an external lookup, rather than something static that is populated at startup time. Is that because you expect the database to be very regularly updated (hourly not monthly)?

I'm going to close #997 in favor of this ticket. If this enrichment is dependent on that external API, you would need to release that either as a commercial service or as an open-source GitHub repo so that the wider community can leverage this enrichment...

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/116
