### ISSUE TITLE
LZO support

### ISSUE THREAD

**Issue by spy-tech** [snowplow/snowplow#2988]
In the S3 kinesis configuration there is the following:

```
# Format is one of lzo or gzip
# Note, that you can use gzip only for enriched data stream.
```
Can you please clarify the above in the documentation, since it is rather ambiguous? Since gzip is not a splittable file format, it seems that it won't scale. I.e., that the processing capabilities of all the real-time events would be very limited in throughput. There are a bunch of tickets open regarding LZO support, but those don't really talk about the soft real-time infrastructure. I'd rather not sit with a pile of LZO data, which doesn't actually work. 

As such, I would like to see some small paragraph in the documentation explaining why gzip support exists in the first place and additionally why there is no splittable file support.

**Comment by alexanderdean** [comment]
Hi @spy-tech - you are right, this part of the Snowplow setup is quite confusing.

First we need to define our terms:

* Kinesis S3's LZO support takes a set of Kinesis records, treats them as byte arrays, and boxes them in Twitter's Splittable LZO envelope. As well as LZO files, Kinesis S3 also outputs LZO.index files which can be optionally used for more performant processing in Hadoop
* Kinesis S3's GZIP support takes a set of Kinesis records, treats them as UTF8 strings, writes them to newline-delimited files and then gzips them

The output of Kinesis S3's LZO support is designed to be compatible with Snowplow's Hadoop enrichment pipeline, in support of our [Lambda architecture](﻿﻿http://discourse.snowplowanalytics.com/t/how-to-setup-a-lambda-architecture-for-snowplow/249). So you put a LZO-configured Kinesis S3 on the raw event stream, and the payloads sunk to S3 can be read by Scala Hadoop Enrich in the Snowplow Hadoop pipeline.

By contrast, Snowplow's Scala Hadoop Shred process expects to run on a folder of gzipped or raw newline-delimited Snowplow enriched events, which are UTF8 Strings. This in theory makes Kinesis S3's GZIP support a good fit for loading Redshift from the enriched event stream (by using Scala Hadoop Shred plus the StorageLoader). I say theoretically because we don't do this ourselves (we run the standard Lambda architecture from the wiki page above).

On to your questions:

> Since gzip is not a splittable file format, it seems that it won't scale. I.e., that the processing capabilities of all the real-time events would be very limited in throughput.

I'm not sure I follow. Once you have written your Kinesis records to S3, they are outside of the real-time pipeline. Kinesis S3 has no problem keeping up with the incoming stream and writing it out to compressed files.

> I'd rather not sit with a pile of LZO data, which doesn't actually work.

Work for what? If you have LZO data for your collector payloads, it will work fine. If you have GZIP data for your enriched events, it will probably work with Scala Hadoop Shred. We haven't implemented any other use cases for data in S3 currently.

> why gzip support exists in the first place

The GZIP support was added by @kazjote - so probably best to ask him about his use case (remember Kinesis S3 is not a Snowplow-exclusive project).

> why there is no splittable file support

Do you mean why we haven't used Twitter's Splittable LZO envelope for our enriched events? It's a good question - I haven't really thought about this before. The truth is that the enriched event format needs a lot of revision - so we should definitely consider compression formats (including row-wise versus column-wise) as part of this.

**Comment by kazjote** [comment]
> >  why gzip support exists in the first place

> The GZIP support was added by @kazjote - so probably best to ask him about his use case (remember Kinesis S3 is not a Snowplow-exclusive project).

Our use case is very simple. We are processing enriched events with Spark. We do not need to load it into Redshift or any other data store (well we load it to Elastic Search in fact). Implementing gzip support in Kinesis S3 was the easiest way to persist enriched events in S3 at that time.

However, now there seems to be easier way with AWS Firehose and AWS Lambda. You can move any data from Kinesis stream to Firehose using this Lambda function: https://github.com/awslabs/lambda-streams-to-firehose from AWS Labs.

Firehose compresses Kinesis records and persists to S3. It is simplier as you don't have to run any process on your instances.

**Comment by alexanderdean** [comment]
Thanks for sharing that @kazjote - helpful context...
