### ISSUE TITLE
EmrEtlRunner: add --resume-from option

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3128]
Since everything will take place on emr, I don't think it makes sense to still have this option.
Someone contradict me if I'm wrong.

**Comment by alexanderdean** [comment]
* The global `--skip emr` makes no sense, agree
* I think the ability to skip individual steps doesn't make sense because the whole pipeline is linear - out of `A,B,C,D,E,F`, it doesn't make sense to do `A,B,D,E`
* However, it **is** still important though to be able to resume from partway through (`--startFrom` ?), because if there is a failure you need to have the ability to resume from partway through the job

So maybe this ticket is about replacing `--skip` with `--startFrom`/`--resumeFrom`?

**Comment by alexanderdean** [comment]
We've changed our mind on this - having the option to still `--skip` steps gives us more flexibility, especially in terms of migrations.

**Comment by alexanderdean** [comment]
Fixed the ticket name, please update the commit too
