### ISSUE TITLE
EmrEtlRunner: turn empty S3 directory detections through Sluice into EMR steps

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3130]

**Comment by alexanderdean** [comment]
This brings up-to-date EmrEtlRunner's "dead man's handle" detection of existing data in the pipeline, where the existence of that data means that a previous run is ongoing (or has failed partway through). EmrEtlRunner uses this detection to prevent itself from running.

In fact, this is a flawed approach. The problem is that the existence of data in the checked folders is not a sufficient check to determine whether another pipeline run is ongoing (or failed). This is because it takes an amount of time to boot a new pipeline run in EMR, during which time no data has been written, and so this prior ongoing run cannot be detected.

This was a far smaller problem before #276, because previously the file moves were done by Sluice, and the file moves to processing folder were commenced within a few second of startup, so the window for this race condition was just a few seconds, not 5-12 minutes.

The better alternative to this ticket is to use an end-to-end locking mechanism, similar to the locking mechanism found in Dataflow Runner.

**Comment by alexanderdean** [comment]
De-scheduling
