### ISSUE TITLE
Spark Enrich: fix CurrencyConversionTransactionSpec

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3225]
```json
"errors":[
  {
    "level":"error",
    "message":"error: object instance has properties which are not allowed by the schema: [\"counts\",\"page\"]\n    level: \"error\"\n    schema: {\"loadingURI\":\"#\",\"pointer\":\"\"}\n    instance: {\"pointer\":\"\"}\n    domain: \"validation\"\n    keyword: \"additionalProperties\"\n    unwanted: [\"counts\",\"page\"]\n"
  },
  {
    "level":"error",
    "message":"error: object has missing required properties ([\"data\",\"schema\"])\n    level: \"error\"\n    schema: {\"loadingURI\":\"#\",\"pointer\":\"\"}\n    instance: {\"pointer\":\"\"}\n    domain: \"validation\"\n    keyword: \"required\"\n    required: [\"data\",\"schema\"]\n    missing: [\"data\",\"schema\"]\n"
  }
]
```

Seems to be caused by https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-hadoop-enrich/src/test/scala/com.snowplowanalytics.snowplow.enrich.hadoop/good/CurrencyConversionTransactionSpec.scala#L95

@chuwy do you think I can get rid of it?

**Comment by chuwy** [comment]
This is quite interesting. I don't know if @BenFradet already realized this, but here's how I see it.

Inputs:
1. Test expectation doesn't meet result because TSV lengths mismatch. Expectation has 124 fields. Also expectation has ecommerce transaction within JSON, which is not the case anymore - it should be separate TSV columns.
2. Test isn't running if OEM_KEY isn't set.
3. We set OEM_KEY on Travis, but it tests only SCE, not Enrich job
4. Previously @alexanderdean was publishing Enrich job manually
5. We added CI/CD to Enrich job at R86 Petra, but we didn't publish Enrich since R83, so test still was not running.

So, my conclusion is that this test is not valid for a long time, but we didn't notice it because it was never running.

**Comment by alexanderdean** [comment]
Sounds right to me! I'm not surprised we are finding a few remaining skeletons in our test suite :-)

**Comment by BenFradet** [comment]
yup, I think it never worked too, just as #3224

**Comment by BenFradet** [comment]
woops didn't mean to close this
