### ISSUE TITLE
RDB Loader: simplify configuration

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3279]
At the moment the whole EmrEtlRunner configuration has to be passed in. This is problematic for a few reasons:

1. It creates an unnecessary dependency between EmrEtlRunner releases and RDB Loader releases
2. It increases the code/test surface area of RDB Loader unnecessarily
3. It makes it difficult to add new configuration options for RDB Loader that EmrEtlRunner doesn't care about
4. It means an odd dependency on the batch pipeline when we start running the RDB Loader in real-time pipelines (why should my real-time pipeline on Azure care about a configuration file for something called the EmrEtlRunner?)

**Comment by chuwy** [comment]
Although whole configuration (except AWS creds since rc3) file is passed to RDB Loader, it does not require whole configuration to be present/valid. If config file misses whole `aws.emr.jobflow` section - RDB Loader doesn't care it will accept it as valid.

But RDB Loader requires config properties from very different parts of config file: `aws.s3.buckets.jsonpath_assets`, `aws.s3.buckets.shredded.good`, `aws.emr.region`, `storage.versions`, `monitoring.snowplow` etc. So we could generate separate config file for RDB Loader on-fly.

**Comment by alexanderdean** [comment]
Right - the easiest way to fix this is to forget about EmrEtlRunner, think about what properties are needed and then think what would the HOCON file look like if we writing this as a RT pipeline service today...

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/snowplow-rdb-loader/issues/21
