### ISSUE TITLE
RDB Loader: Inconsistent resolution of Snowplow-hosted jsonpaths

### ISSUE THREAD

**Issue by acgray** [snowplow/snowplow#3378]
https://github.com/snowplow/snowplow/blob/8e5e1901af4c9073d0dceda2e2450ea6e6b486bb/4-storage/rdb-loader/src/main/scala/com/snowplowanalytics/snowplow/rdbloader/ShreddedType.scala#L158

The RDB Loader is hard-coded to use `s3://snowplow-hosted-assets[-region]` to retrieve jsonpaths for Snowplow-authored jsonschemas.

This seems inconsistent with other Snowplow components which use the configurable value in config.yaml (aws/s3/buckets/assets) and with the Iglu model in which each repo has its own `jsonpaths` store.

Is there a reason for this?  If not I am happy to write a PR.

**Comment by chuwy** [comment]
Hey @acgray,

RDB Loader attempts to load JSONPaths assets from `s3://snowplow-hosted-assets[-region]` only if:

1. No assets were found at custom `jsonpaths` bucket OR
2. No custom assets were specified at all

Is this issue something you encountered in production?

**Comment by acgray** [comment]
It's not a huge issue but we mirror `snowplow-hosted-assets` internally and also have our own Iglu central fork, and it would be nice to be able to use those globally.

**Comment by chuwy** [comment]
Sorry, @acgray, I'm still not following. You still can use [`aws.s3.buckets.jsonpath_assets` setting](https://github.com/snowplow/snowplow/blob/master/3-enrich/emr-etl-runner/config/config.yml.sample#L9) in `config.yml` to point RDB Loader to your mirror. If your mirror is identical to `snowplow-hosted-assets` then it won't ever reach our bucket, because custom assets bucket (`jsonpath_assets`) is always prioritized. This is how StorageLoader worked and I see it's quite consistent with other parts of pipeline. Please, correct me if I missing something.

You're totally right at this point. We're working on providing more consistent (and format-independent) approach to work with Iglu registries. But so far, there's no clear direction for this problem. I cannot give you any clues or ETA so far to not also give false promises, but you can be sure - we're agree and working on that.

**Comment by acgray** [comment]
Correct - however if we used the `aws.s3.buckets.jsonpath_assets` setting for our `snowplow-hosted-assets` mirror we would have to add our custom jsonpaths to the same bucket alongside the mirrored assets under `4-storage/redshift-storage/jsonpaths` which isn't very clean (I'd rather our mirror was a pristine copy).

**Comment by chuwy** [comment]
Hey @acgray. I'm moving this into new repository, let's continue discussion there: https://github.com/snowplow/snowplow-rdb-loader/issues/4
