### ISSUE TITLE
EmrEtlRunner: release lock in case of no-op

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3396]
e.g. `NoDataToProcessError`

**Comment by alexanderdean** [comment]
This is an urgent fix. R92 is very fragile without this.

**Comment by BenFradet** [comment]
@alexanderdean there is only `NoDataToProcessError` right?

**Comment by alexanderdean** [comment]
Hmm. Is there a reason why we wouldn't follow the same behavior for the other no-ops? Here is a (admittedly tenuous) scenario:

1. User is running without lock, RunA
2. Data is in enriched
3. User upgrades to using lock
4. New job starts, RunB, creates lock but no-ops because it finds data in enriched
5. RunA completes but doesn't delete lock
6. RunC+ cannot start because RunB did not delete lock

Thoughts?

**Comment by BenFradet** [comment]
I guess the problem was that which cases were no-ops and which weren't was not clear to me.

Am I right that no-ops are limited to the following scenarii:

- in buckets without data
- enrich good not empty
- shred good not empty

?

**Comment by alexanderdean** [comment]
Correct - no-ops are fundamentally limited to these:

https://github.com/snowplow/snowplow/blob/master/3-enrich/emr-etl-runner/bin/snowplow-emr-etl-runner#L97-L104

You should be able to work back to the original exception throw-sites...
