### ISSUE TITLE
EmrEtlRunner: treat archive_enriched and archive_shredded as separate steps

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3401]
At the moment we confusingly use the `archive_enriched` step to refer to archiving enriched and shredded. This is problematic if a user is running Snowplow without shredding & loading data into Redshift, because:

1. If we disable `archive_enriched`, then the enriched events are left in that folder and the next run can't start
2. If we *don't* disable `archive_shredded`, then the S3DistCp trying to move the shredded data will fail due to no data being present

Note that I am open to other suggestions (e.g. hardening the S3DistCp step), but the solution of *treat archive_enriched and archive_shredded as separate steps* seems fairly clean and simple.

**Comment by BenFradet** [comment]
The current behavior is:

if we skip `archive_enriched`, we don't do any archiving of either enrich or shred
otherwise:
&nbsp;&nbsp;if `enrich`we archive enrich and shred for the current run id
&nbsp;&nbsp;otherwise we archive enrich and shred for the last run id

Do we want to convert that to:

if we skip `archive_enriched`, we don't archive enrich
otherwise:
&nbsp;&nbsp;if `enrich` we archive enrich for the current run id
&nbsp;&nbsp;otherwise we archive enrich for the last run id

and

if we skip `archive_shredded`, we don't archive shred
otherwise:
&nbsp;&nbsp;if `shred` we archive shred for the current run id
&nbsp;&nbsp;otherwise we archive shred for the last run id

?

**Comment by alexanderdean** [comment]
Can you clarify the nested booleans, "if `enrich`" and "if `shred`". What conditions are you referring to here?

**Comment by BenFradet** [comment]
I'm referring to https://github.com/snowplow/snowplow/blob/master/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/runner.rb#L70-L76

ping @chuwy

**Comment by alexanderdean** [comment]
I think @chuwy wrote this recovery code? I'm not familiar with it.

**Comment by BenFradet** [comment]
yup

**Comment by chuwy** [comment]
Sorry for delay here.

Regarding code: if we're in `recover` mode - we don't know exact run id to archive (because timestamp is logst) therefore S3DistCp archives latest found directory; `pipeline` mode means we're in usual pipeline run and run id is known.

EmrEtlRunner can decides we're in `recovery` mode iff `archive_enriched` is present and `enrich` is absent.

Does it answer a question?

**Comment by alexanderdean** [comment]
Would you guys mind jumping on a Zoom together? Can be tomorrow morning of course, but I we can't afford to introduce a regression here...
