### ISSUE TITLE
EmrEtlRunner: replace Sluice by aws-sdk-s3

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3524]
This is blocking us from migrating every path to s3a since Sluice doesn't handle s3a paths and is making empty checks in emr etl runner.

**Comment by alexanderdean** [comment]
Ah good catch

**Comment by alexanderdean** [comment]
Potentially we could re-write these to use Java? This would be way more performant.

**Comment by BenFradet** [comment]
Ideally we'd just wouldn't do empty checks in eer, this leads to unnecessary memory problems

**Comment by jbeemster** [comment]
Part of the issue is likely due to how empty checks are performed - the function lists __all__ files in the bucket to fetch the length.  Non-empty check only need to assert that some non-zero byte files are available rather than listing everything in the bucket.

> https://github.com/snowplow-archive/sluice/blob/master/lib/sluice/storage/s3/s3.rb#L128

Example of this implemented in Scala:

> https://github.com/snowplow-devops/operations-server/blob/master/2-servers/operations-server/src/main/scala/com.snowplowanalytics.devops/operationsserver/implementations/clients/AwsClient.scala#L186-L230
