### ISSUE TITLE
Add indexes for Postgres event table

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#356]
Need to investigate what indexing makes sense.

**Comment by smugryan** [comment]
It's probably also worth investigating Redshift performance tuning as Redshift is postgresql-like and not 100% postgresql (no such thing as a real index in Redshift). I say this because Snowplow has Redshift as a recommended storage platform and anything they know can help many customers.

Currently we're working on improving performance for a few clusters running 2 to 16 machines with > 300 million rows (growing 20 million rows/day). Amazon sent us some information on tuning that could be linked to or the Snowplow docs could contain some best practices for tuning Redshift databases.

http://docs.aws.amazon.com/redshift/latest/dg/tutorial-tuning-tables.html

**Comment by EZWrighter** [comment]
I know this is pretty old, but I will add a note here.  We have about 7 million rows and ran into a huge delay in very simple queries to count events (1 -2 minutes).  We segment based on app_id, so putting an index on app_id brought queries under a second.  Not sure if there are going to be any long term issues with having that index, but so far it has fixed the slow query issues we were having.  Waiting to see if there are implications when adding new rows.

**Comment by alexanderdean** [comment]
Closing as superceded by new PG Loader
