### ISSUE TITLE
Scala Common Enrich: remove user-agent-utils enrichment

### ISSUE THREAD

**Issue by rgantidl** [snowplow/snowplow#3591]
The page on bitwalker says this project is being end of lifed
http://www.bitwalker.eu/software/user-agent-utils
Will need to move to an alternate.

**Comment by BenFradet** [comment]
Thanks for pointing it out 👍

**Comment by alexanderdean** [comment]
Yes, this has been end-of-life for a while. It's worth using our other useragent enrichment

**Comment by szareiangm** [comment]
As you know this library has reached EOL. There are some points to discuss after a while:

- @alexanderdean on issue #3656 said that we don't swap the underlying library for the current enrichments. So we might stick to `user-agent-utils`.
- @alexanderdean (#1899, #1900, #1901) suggested that the result of this enrichment should be in its own context table instead of the atomic table.
- There is a great contribution in #3810 to use flexible updatable regex file for `ua_parser`, the alternative. Now it is supercharged.

I was thinking to recommend that we deprecate `user-agent-utils` fields and its enrichment in near future.  There is `ua_parser` as the alternative. During the next months  `user-agent-utils` would not get any updates and its output will be derived from `ua_parser`. This might cause a bit of messy data for analytics. 

What is your opinion about it, folks?

**Comment by BenFradet** [comment]
For me there are two things that need to happen:

- reformat atomic events and so remove those fields (among others), the problem with this is that it breaks a lot of stuff and so will take a lot of time
- either deprecate (and dump the output in a context) or completely remove this enrichment

**Comment by alexanderdean** [comment]
Yep, I would go with deprecating, we have to keep it around for backwards compatibility.

**Comment by BenFradet** [comment]
The atomic events refactor might be a good opportunity to get rid of it though.

Otherwise, it'd mean a jar that is used for an enrichment can never be kicked out which could constitute a security risk since there'd be no way to patch it if it's eol.

**Comment by alexanderdean** [comment]
That's a good point. I think we would deprecate it ("eol") and then remove it a bit later. Key thing is that the legacy data in the enriched events in Redshift still lives somewhere (in the context).

**Comment by alexanderdean** [comment]
So:

* Migrate the structure to a context (part of events refactor)
* Provide a warning on startup that enrichment is eol (suggesting alternatives)
* Stop running enrichment, and remove jar

**Comment by szareiangm** [comment]
@alexanderdean I just thought giving heads up from now would be invaluable to the user community, so I propose this order:
1. Provide a warning on startup that enrichment is eol (suggesting alternatives)
2. Migrate the structure to a context (part of events refactor) -> and fix any code relying on this enrichment.
3. Stop executing enrichment, and remove jar

What do you think?

**Comment by alexanderdean** [comment]
Yep good idea, no need for the warning to be blocked by the refactor

**Comment by BenFradet** [comment]
Regarding the first step, we've:

- published a message on discourse: https://discourse.snowplowanalytics.com/t/user-agent-utils-enrichment-deprecation/2119
- edited the wiki: https://github.com/snowplow/snowplow/wiki/user-agent-utils-enrichment

**Comment by szareiangm** [comment]
@alexanderdean Is there any specific issue ticket for the `events refactor`? 

Perhaps it should be defined as a `Milestone` and scattered issues get attached to it. The milestone is enormous as far as I understood.

**Comment by alexanderdean** [comment]
No, there will be an RFC first.

**Comment by alexanderdean** [comment]
Let's update this ticket name to make clear we are just showing a deprecation warning...

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/79
