### ISSUE TITLE
EmrEtlRunner: add support for shredding from Kinesis S3 Loader's enriched event output

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3606]
The issue here is the absence of a `run=` folder to work with.

**Comment by chuwy** [comment]
Hey @alexanderdean, @BenFradet, here's what I come up with regarding this feature. Would like to brain-storm it and change approach if you have objections as it looks like many EER UX decisions were made.

Basically, this commit:

1. Adds new `buckets.enriched.stream` path in `config.yml` 
2. Makes `buckets.raw` optional as with this "stream mode" `buckets.enriched.stream` is source of data
3. If `buckets.enriched.stream` is defined: `enrich` step doesn't happen at all; instead pipeline starts from special `stage-enriched-stream` step. `staging` and `archive_raw` also never happen.
4. So instead staging,enrich,shred... we now have stage-enriched-stream,shred..., where stage-enriched-stream just copies data to shredder's HDFS directory

This also affects new RDB Loader in many ways mostly because we cannot use `etl_tstamp` anymore.

**Comment by alexanderdean** [comment]
This sounds great @chuwy. Let's discuss with @BenFradet straight after our weekly.
