### ISSUE TITLE
Scala Common Enrich: add salt to PII Enrichment

### ISSUE THREAD

**Issue by falschparker82** [snowplow/snowplow#3648]
**Title was:** *Security Issue: R100 PII pseudonymization is highly suspectible to brute force*

Hey folks,

I've seen your approach at PII pseudonymization for R100 and I have to share my concern that the current way of "pseudonymization" by simple hashing is highly suspectible to brute force, which leads to serious security concerns.

Especially for low cardinality fields like IPv4 addresses, this leads to easy and believable attacks. We're just talking about a search space of 4 bytes, which is about 2 billion different values here. Looking at some recent benchmarks, a combo of consumer grade GPUs currently does 98GH/s on SHA-1 ( https://github.com/kristofferjon/benchmarks/blob/master/16xP104-100-hashcat-benchmark.log ), so it can brute force every single permutation in about 20 milliseconds. Building a reverse lookup table from this and deanonymizing a whole data warehouse is trivial from there.

E-Mail addresses are almost as bad. You could crack all firstname.lastname@domain.com and 6-letter@domain.com addresses for every possible firstname/lastname combination for the top 100 email domains in probably a day.

This is serious.

The only sensible protection against this (and still being able to reverse them later on in a separate database, as you have in mind) would be salting the values with a long and secret salt before hashing, which needs to be a randomly generated string, have at least 128 bits of entropy and be kept secret in the enrichment configuration. If this salt ever gets known to data warehouse users, brute force attacks are just as easy as described above.

Hoping this gets resolved soon.

**Comment by knservis** [comment]
Hashing all possible values is of course possible and trivial, however I would like to understand the attack scenario in which this would happen. Would that scenario involve access to the entire dataset by an unauthorized party? Would it not be just as easy when you have that sort of access to also get the salt? 
The initial thoughts about this functionality is that it help the data processor not have direct access to the name, email or IP address of the data subject without previous justification. When the data subject indicates that they do not wish for their identity to be used, then this data is hashed. 
In any case we could trivially add salt to the hash though the config, however in the case that a rogue actor of the data processor has decided to enumerate all the hashes because they have access, would they not just as likely have access to the salt? 
My understanding is that salt is usually stored with the hash (in password hashes) and it is not supposed to be a secret. If it were to be kept a secret would it not make more sense to use actual cryptography (which may be implemented as an additional strategy in future releases)? Thoughts?

**Comment by yalisassoon** [comment]
Hi @falschparker82 - thanks so much for raising this issue.

@knservis is absolutely right. The purpose of the enrichment is not to prevent a malicious actor who wants to identify individual data subjects in the data. It is to prevent well intentioned data consumers accidentally using the data for a reason that is incompatible with the lawful basis for which the data has been collected. So as a concrete example, a marketer might be using the data to optimize the effectiveness of an ad campaign (by comparing the performance of different variations of the campaign). If the marketer then spotted as part of that analysis that one of the users that had engaged with the campaign had done something interesting that meant they might be susceptible to remarketing, the marketer would not be able to remarket to that user, because e.g. the 3rd party cookie ID necessary to setup that campaign would be obfuscated.

Having said that, the harder we can make it to un-anonymize the data, the better. For that reason I think your suggestion that we enable adding a salt is a great one and we should action it.

**Comment by falschparker82** [comment]
Hi there,

of course, the attack surface around this case is already reduced (otherwise I also would have disclosed more responsibly). We're usually talking about a company internal parameter here, as the data warehouse itself is usually protected.

However, with us for example, we have elevated security and reduced privileges on the Snowplow pipeline itself, while the data warehouse has loosely guarded internal access (i.e. pretty much anyone can make a query). We do this, because we've pseudonymized or anonymized all PII on our own, even before R100.

The attack scenario involves an internal actor with this loosely guarded access. Currently, for example, the IP address is anonymized by truncating the last octet. This is pretty much irreversible. I just wanted to show, that pseudonymizing the IP address by hashing instead might actually make matters *worse*, as the values are now fully reversible by brute force.

We're already talking about the "disgruntled employee"/freelancer case here, which is notoriously hard to defend against, but exporting and analyzing the data in non-intended ways (already made more risky by the pending EU legislation) are also realities that happen in real life. Since the fix here should be rather easy to implement, it would limit this attack scenario to pipeline operators with access to the config — who usually have raw S3 logs access as well anyway.

**Comment by knservis** [comment]
@falschparker82 We could easily add salt. Just a point on the IPv4 which has the smallest domain hence it's trivially enumerable: the PII enrichment runs after all other enrichments. If you have configured dropping the last octet of IPv4 and PII, the hashed value will be the masked value, which of course is even easier to enumerate, but does not uniquely identify the connected machine. 
Can you think of other dimensions that you use in Snowplow where someone can fully enumerate the domain? 
About the S3 logs, we are planning to address that issue too. 
Thanks for your help

**Comment by falschparker82** [comment]
Hi @knservis ,

first off thanks for taking this issue serious, apparently you have thought about a lot of use cases on your own.

However, at ~8.000.000.000.000.000 Hashes per day on a single, non-expensive GPU server, there's a lot of juicy targets out there. Numeric, ascending `user_id`s are definitely at risk, also sufficiently truncated and formatted geoip data probably and anything easily enumeratable (like user_agents or second-level timestamps) falls into this category. Anything UUID-like with sufficient entropy, (like the fingerprints, event_ids, UUIDv4 type `user_id`s etc.) is probably fine.

**Comment by alexanderdean** [comment]
Thanks for the thorough report @falschparker82, much appreciated.

I've renamed this ticket and assigned it to the next GDPR milestone, which @knservis is working through. A basic enrichment-configuration-based salt should get us started, although we are interested in more sophisticated salts which incorporate a canonical user ID as well.

Information security is a process, not a single hero feature or release. It's great that we are getting thoughtful feedback like @falschparker82's, and that we can then quickly feed that into our further GDPR-oriented releases. Thanks again!

**Comment by alexanderdean** [comment]
Note: the salt should not be directly stored in the enrichment configuration, but should be retrieved from AWS. See @chuwy's storage loader configurations for guidance.

**Comment by knservis** [comment]
@alexanderdean That is better that config for sure. @chuwy are there any considerations when using AWS Systems Manager Parameter Store (especially not impeding the support of other platforms such as Google Cloud)?

**Comment by chuwy** [comment]
That's a broad question, but generally no, AWS Parameter Store is designed for use cases like this, with careful role-management I don't see any shortcomings.

As of other platforms - most of them provide similar services, e.g. Google [Cloud KMS](https://cloud.google.com/kms/docs/encrypt-decrypt). In configuration it'll be just:

```
{
  "salt": {
    "cloudKms": {
      "parameterName": "foo"
    }
  }
}
```

instead of 

```
{
  "salt": {
    "ec2ParameterStore": {
      "parameterName": "foo"
    }
  }
}
```

**Comment by alexanderdean** [comment]
`googleCloudKms` :-)

**Comment by knservis** [comment]
@alexanderdean It would make testing easier if we optionally have either "ec2ParameterStore" and "localValue", with the local value having the actual salt. Do you see something wrong with that?

**Comment by alexanderdean** [comment]
I think that's fair. @chuwy do we support the same with the loader configs?

**Comment by chuwy** [comment]
@alexanderdean, @knservis I thinks so. It is [defined](https://github.com/snowplow/iglu-central/blob/8a44c504c3ccd82707ec9cd9f1bd10f02f573a5e/schemas/com.snowplowanalytics.snowplow.storage/redshift_config/jsonschema/3-0-0#L46-L64) as `"type": ["string", "object"]`, so it is either "plain value" or "reach some service and decrypt this key to get actual secret".

**Comment by alexanderdean** [comment]
Makes sense, let's do that here too.

**Comment by knservis** [comment]
@alexanderdean @chuwy I have added the salt to v2-0-0 of the config https://github.com/snowplow/iglu-central/pull/708
