### ISSUE TITLE
Scala Common Enrich: add validation for contexts added by enrichments

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3795]
API Request enrichment works on *already* validated contexts and self-described events and does not validate produced contexts, therefore there's always a chance that output data won't correspond to `outputs.schema`.

**Comment by chuwy** [comment]
- [ ] Check same for SQL Query enrichment

**Comment by benjben** [comment]
Hey @chuwy , we talked about this with Customer Squad, that will be in charge of displaying the errors, and we think that this type of error should be a subtype of `EnrichmentFailure`, like `InvalidContext`, because an enrichment that creates a wrong context is a problem with this enrichment. After each enrichment, we would check the context that it added and if it's not valid we create this type of bad row and stop the processing. WDYT?

**Comment by chuwy** [comment]
Hey @benjben, sorry missed your last message. As we discussed in internal RFC doc yesterday, there are many more oppostunities for loaders to fail. Biggest ones are:

* Unavailable (or wrong version of) Iglu Registry. Loaders have their own requirements for registries
* Unavailable DB. BQ failed inserts exist because BigQuery was unavailable
* Bug in a shredding/casting algorithm
* Improperly versioned schema

**Comment by chuwy** [comment]
Possible duplicate: https://github.com/snowplow/snowplow/issues/2639
