### ISSUE TITLE
Documentation: add 'Form Body' example of POST request in the Iglu webhook adapter documentation

### ISSUE THREAD

**Issue by dilyand** [snowplow/snowplow#3834]
The documentation currently only shows an example of using the Iglu Webhook via POST request by sending the payload as a JSON object. The adapter also supports sending the payload in URL-encoded querystring format but we're missing an example for that.

```
curl -v -X POST \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'user=6353af9b-e288-4cf3-9f1c-b377a9c84dac&name=download&publisher_name=Organic&source=source&tracking_id=id&ad_unit=unit' \
  127.0.0.1:8080/com.snowplowanalytics.iglu/v1\?schema\=iglu%3Acom.acme%2Fcampaign%2Fjsonschema%2F1-0-0
```

**Comment by paulboocock** [comment]
This page now includes GET and POST examples: https://docs.snowplowanalytics.com/docs/collecting-data/collecting-data-from-third-parties/iglu-webhook/

**Comment by dilyand** [comment]
We still seem to be missing that particular example: a POST request, but the payload is not sent as a JSON blob but as 'form body'.

**Comment by paulboocock** [comment]
Ah I misunderstood! From the issue description I thought you were looking for an example with querystring parameters but the title makes it rather obvious that this isn't at all what this issue is about 🤦‍♂️

Anyway, I've updated this page now 🙂 https://docs.snowplowanalytics.com/docs/collecting-data/collecting-data-from-third-parties/iglu-webhook/
