### ISSUE TITLE
Scala Common Enrich: disallow event mutation in the JS enrichment

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3913]

**Comment by alexanderdean** [comment]
This is no doubt a good idea!

**Comment by miike** [comment]
Can mutation be added as an option (defaulting to false in the JS config?) as I suspect there's quite a few JS enrichments mutating events even if that's not ideal.

**Comment by chuwy** [comment]
The whole point of raising this issue was that we could be able to guarantee that once enrich step has finished - event is valid and anything downstream can work with it without re-validating. Ability to mutate an event is what makes it much harder to give this sort of guarantee.

I believe that main use-case of mutation in JS enrichment is fixing bad rows on-fly. And if that is the case then I'm even more sure that JS enrichment shouldn't be able to mutate events and this process should be factored out into bad data recovery (which should be much easier if we have mentioned guarantee). If that is not the case - I'm happy to discuss other ways.

**Comment by colmsnowplow** [comment]
>  the user should have some input into what occurs so this doesn't break existing JS enrichments that do mutate an event (e.g., warn, go to bad rows, hard fail etc).

This, in fact, isn't a bad idea for all similar enrichments. For example, if I want to use the API enrichment with a third party service I have no guarantee they'll output valid data every time, if I want to set up the SQL enrichment I may not be guaranteed that the other SQL DB will have 100% uptime or no concurrent process which causes a 404.

The option to simply not add the derived context in such cases would probably be useful.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/18
