### ISSUE TITLE
Scala Stream Collector: provide a way to specify custom path mappings

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#4087]
e.g.

```
com.acme/track -> com.snowplowanalytics.snowplow/tp2
com.acme/redirect -> r/tp2
com.acme/iglu -> com.snowplowanalytics.iglu/v1
```

**Comment by alexanderdean** [comment]
This is really cool! I agree this should go in SSC not SE, but can we document the decision just so we have the reason for posterity.

**Comment by BenFradet** [comment]
I think the major concern is around composition:

If you have one mapping from A -> B and another from B -> C (in time), you couldn't reprocess A -> C in one go

That could lead to headaches with the major source of reprocessing: recovery.

**Comment by alexanderdean** [comment]
I think I get it - so you are saying that any given X -> Y mapping at a point in time should be "locked" into the raw event rather than be an at-enrich overlay?

**Comment by dilyand** [comment]
With a [few exceptions](https://github.com/snowplow/snowplow/blob/master/2-collectors/scala-stream-collector/core/src/main/scala/com.snowplowanalytics.snowplow.collectors.scalastream/CollectorRoute.scala#L145-L167), we do not allow in `0.15.0` any path consisting of one or more than two segments to be used in requests or responses. If we encounter such a case, we [increment the failed requests counter and return a `404`](https://github.com/snowplow/snowplow/blob/master/2-collectors/scala-stream-collector/core/src/main/scala/com.snowplowanalytics.snowplow.collectors.scalastream/CollectorRoute.scala#L107-L109).

The point of this appears to be so that we can match against the `vendor/version` protocol.

aee002a retains this behaviour. So the mappings at the start of this thread will be now possible, but users won't be able to map, e.g.:

```
com.acme/track/snplow -> com.snowplowanalytics.snowplow/tp2
redirect -> r/tp2
```

If in future we want to allow a truly arbitrary path to be used, we need to decide what we want to do with paths that have no match in the configured mappings. The current behaviour in `0.15.0` (where there are no mappings at all) and in `0.16.0-rc2` (where mappings are optional), is to respond with a cookie to requests with two-segment paths; and to respond with `404` for single- and multi-segment paths (except in the cases specified in the beginning of this comment).

Should any path, regardless of how many segments it has, result in a `404` if it cannot be mapped? Or should two-segment paths continue to receive a cookie response even if no mapping is provided for them -- to allow for custom webhooks downstream?

**Comment by yalisassoon** [comment]
@dilyand that's absolutely fine - we just need to make it clear in the documentation that custom paths must be of the form `string1/string2`
