### ISSUE TITLE
Enforce tracker as a singleton object

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/snowplow#4126]
Failure to implement the tracker as a singleton object leads to a race condition. 

The Android tracker enforces this, the iOS should follow suit - it's a much better user experience to use the tracker without needing to handle this.

**Comment by chuwy** [comment]
Hi @colmsnowplow, why is it specifically required for _all_ trackers? I don't see any problem with non-singleton objects in Python or Scala trackers because they don't share any state and therefore users can have as many trackers and emitters as they want. If iOS tracker shares some mutable state, maybe its better to create a ticket in its own bugtracker?

**Comment by colmsnowplow** [comment]
Ah - actually I meant to create this ticket in the iOS repo, not snowplow/snowplow. Apologies, closing this and will open one in the appropriate place!
