### ISSUE TITLE
Scala Common Enrich: bump snowplow-badrows to 0.1.0-M4

### ISSUE THREAD

**Issue by benjben** [snowplow/snowplow#4216]

**Comment by chuwy** [comment]
Given that `snowplow-badrows` wasn't a part of previous releases, I don't think we should have a ticket for bumping it.

**Comment by benjben** [comment]
You're right. I'm in an annoying situation, in R118 branch there is:
```
d51b1ce25 [WIP] Scala Common Enrich: use snowplow-badrows (closes #4106)
...
e068d68d3 Scala Common Enrich: add additional metadata to enrichment stage bad rows (closes #4120)
...
faf6fcd26 Scala Common Enrich: bump snowplow-badrows to 0.1.0-M4 (closes #4216)
```
I can't fixup the last commit (with all the refactoring of bad rows) in the first one when rebasing because in between there are commits that update parts of SCE using bad rows.

When the PR will be code complete I'll try to solve this.

**Comment by chuwy** [comment]
Yeah, I know this situation. I usually "solve" this by squashing changes into a latest commiit that doesn't introduce conflicts (given that we're talking about big amount of conflicts).

I think the purpose of CHANGELOG is to give a user precise summary of what has been changed since _previous release_ and squashing things into a slightly irrelevant commit is least of two evils.

But in this situation honestly, I'd squash #4120 into #4106 as well, especially having that implementation is so tiny.

**Comment by benjben** [comment]
That makes totally sense, I will do that. Thanks @chuwy !!

**Comment by benjben** [comment]
Handled by #4106
