### ISSUE TITLE
Scala Common Enrich: make it possible to reload enrichments configuration in runtime

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#4247]
Enrichments are stored in KV storage and driver has a simple HTTP endpoint, by hitting which a 3rd party app can force an enricher to reload enrichments.

We technically could post whole new enrichments config, but see it as a security concern.

**Comment by jbeemster** [comment]
The way we deploy enrichment servers in clusters would make POSTing updates a pain in any case.  Some sort of change listener in the Enrichments would be the best fit for how we manage enrichments in production where it would simply know when the enrichment has changed in its remote store (i.e local file / dynamodb) and reloads accordingly.

If this was configurable you could then turn off the change listener so that you can maintain current behaviour and remove the security concerns.

Would be a very exciting change in any case to be able to dynamically reload enrichments!

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/49
