### ISSUE TITLE
The android setup page should be updated

### ISSUE THREAD

**Issue by shumidub** [snowplow/snowplow#4340]
The https://github.com/snowplow/snowplow/wiki/Android-tracker-Setup page should be updated (android tracker version, maybe proguard rule and other)

**Comment by AlexBenny** [comment]
Hi @shumidub , thanks for raising the issue.
We are migrating all the documentation of the trackers here: https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/
It's in a review phase so not everything is migrated yet.

Also, the repository of the Android tracker has been moved here: https://github.com/snowplow/snowplow-android-tracker

You can also send us questions here: https://discourse.snowplowanalytics.com/

We keep a note of you useful feedback!
I'm closing the issue here.
For further questions or feedback, please, don't hesitate to contact us on Discourse or in the tracker repository.

**Comment by goodits** [comment]
Sorry for the confusion @shumidub. We're going to step up efforts on deprecating the old docs and signposting to the new.
