### ISSUE TITLE
Restore CHANGELOG

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#4433]
In a recent tidy-up of this repo we lost the `CHANGELOG` in the root.

I think this is a shame, for two reasons:

1. We lost a visible historical record ("it's in the git history" doesn't count as visible) of the evolution of our core IP over the past 8 years
2. We have lost a prominent place to log the ongoing changes we are making to this repo (for example @adatzer's great work on discoverability via git submodule updates)

I propose:

* Resurrecting the historic CHANGELOG
* Backfilling entries since its deletion
* Adding new entries as we make updates to this repo

For new entries in the CHANGELOG, I would propose simply datestamping them given that they don't fall under specific release numbers any more (there is no global Snowplow release version at the level of this repo currently - we don't offer LTS / blessed bundles to OSS yet).

**Comment by paulboocock** [comment]
We should do this (and automate it) when we automate the updating of the submodules, which we've just started working on (cc @adatzer). 

I'd suggest introducing a CHANGELOG.json too as this will make autogenerating the CHANGELOG.md far easier and more reliable.

**Comment by benjben** [comment]
In the tidy-up of this repo I had deleted the `CHANGELOG` on purpose because I failed to see the need for it in a post world umbrella releases world, but I can now see the value.

I think that it would be great to automatically update it as such : unless I'm missing something, a submodule will get updated only when new commits are available on the `master` branch of the child repo. This happens only when there has been a new release of a component. In this case the latest commit should always be named `Prepare for release x.y.x` according to our workflow. We could then take this version `x.y.z` and add one line to the `CHANGELOG` when this happens, like below :

```
2021-03-08 - snowplow/stream-collector - Release 2.2.0
2020-11-20 - snowplow/enrich - Release 1.4.2
2020-08-27 - snowplow/iglu-scala-client - Release 1.0.2
2020-07-22 - snowplow-incubator/snowplow-badrows - Release 2.1.0
```

I think that `snowplow/snowplow` should still get all the commits all the child repos and not only the `Prepare for release` commits.

How does that sound?

**Comment by adatzer** [comment]
Indeed @benjben that would be definitely possible. 
There is the concern of it just repeating the commits history without a wrapping story, so maybe we could just restore it for now and reconsider its automation in relation to a possible "release" style? cc @paulboocock

**Comment by benjben** [comment]
Indeed it would be great to perform some kind of aggregation. We could have an other Github Action just in charge of updating the CHANGELOG that would run for instance every Sunday and if there were some updates during the week, add something like

```
2021 - Week 12
---------------------
snowplow/stream-collector - Release 2.2.0
snowplow-incubator/snowplow-badrows - Release 2.1.0
```

The issue with this approach is that it would require a commit to update the CHANGELOG.

If we don't want to have this additional commit, we could do this in the same action that updates the submodules : when a submodule gets updated, if CHANGELOG has been updated more recently than a week ago, don't touch it, if it was updated more than a week ago, then update it with all the changes since last update.

**Comment by paulboocock** [comment]
With the new release cadence to help us tell our story better, I'm going to suggest we hold off on automating the top level changelog so we can reduce the noise they I anticipate automating a changelog will create. I really like Bens latest idea but I'd love it if we could highlight the things in that release to tell the story - maybe even going beyond that and telling the story of that month/quarter/etc for a collection of releases. 

With that in mind, I don't think we can automate it yet (or ever perhaps) but we can ensure the CHANGELOG is updated with the important issues that have happened between our "blessed" releases.

**Comment by alexanderdean** [comment]
Maybe we put a placeholder at the top of the CHANGELOG explaining what we are planning and linking off elsewhere (`/releases`?) until such time as we have the more narrative-driven version...
