### ISSUE TITLE
Upgrading snowplow enricher library from 0.38.0_Scala_2_11 to 3.6.0_Scala_2_12

### ISSUE THREAD

**Issue by tajdars** [snowplow/snowplow#4556]
Hello, 

I'm trying to upgrade snowplow enricher dependency in a java app 

Running into several  issues such as change of data type, classes moved etc.

One major change is the signature of com.snowplowanalytics.snowplow.enrich.common.loaders.ThriftLoader
        .toCollectorPayload();
which requires a Processor in addition to byte[]

Are there any examples around what to  pass here ?
Is this upgrade feasible ?

**Comment by benjben** [comment]
Hi @tajdars ,

I'll answer here, but please use https://discourse.snowplow.io/ to ask questions.

> change of data type, classes moved etc.

Indeed 0.38.0 is 3 years old and there were a lot of changes since then. Most notably there is a [new bad row format](https://snowplow.io/blog/snowplow-release-r118-badrows/#badrows) since 1.0.0.

> One major change is the signature of com.snowplowanalytics.snowplow.enrich.common.loaders.ThriftLoader
.toCollectorPayload(); which requires a Processor in addition to byte[]

`Processor` is related to the new bad row format mentioned above. Its purpose is to identify the app emitting a bad row. It is defined [here](https://github.com/snowplow/snowplow-badrows/blob/master/src/main/scala/com.snowplowanalytics.snowplow.badrows/Processor.scala#L18).

> Are there any examples around what to pass here ?
> Is this upgrade feasible ?

Yes it is feasible ! You can find some examples here:
- https://github.com/snowplow/enrich/blob/master/modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/EtlPipelineSpec.scala#L77
- https://github.com/snowplow/enrich/blob/master/modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/EtlPipelineSpec.scala#L97
- https://github.com/snowplow/enrich/blob/master/modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/loaders/ThriftLoaderSpec.scala#L37

May I ask, what is your use case for using Enrich library ?

**Comment by tajdars** [comment]
hi @benjben thank you for your response. 

Use case is upgrading the snowplow dependency in a java(flink) app. 

Are there any java  based test cases  ? That would be super helpful in understanding the usage.

Thanx,

**Comment by benjben** [comment]
> Are there any java based test cases ?

Not too my knowledge sorry, as our whole codebase is in Scala. But this is just about passing parameters to a function, so you should be able to get it to work even in Java.

**Comment by tajdars** [comment]
Thanx @benjben , tried to figure things out and am stuck around these lines 
(test)
com.snowplowanalytics.snowplow.enrich.common.EtlPipelineSpec

lines 49-54:


  val adapterRegistry = new AdapterRegistry()
  val enrichmentReg = EnrichmentRegistry[Id]()
  val igluCentral = Registry.IgluCentral
  val client = IgluCirceClient.fromResolver[Id](Resolver(List(igluCentral), None), cacheSize = 0)
  val processor = Processor("sce-test-suite", "1.0.0")
  val dateTime = DateTime.now()


Our schemas are not sourced from any kind of schema repo, but are bundled.

**Comment by tajdars** [comment]
Hi @benjben 

Any thoughts on how to import (dependencies etc.)

**import cats.Id**

on the java side ?

**Comment by spenes** [comment]
Hey @tajdars, using Java library in Scala application would be okay but using Scala library in Java application is kinda uncharted territory because Scala has more expressive type system than Java. Also, we are using [Cats library](https://typelevel.org/cats/) quite heavily in our applications. I am not sure if it is possible to use Cats library in Java at all. You can try to add [this dependency](https://mvnrepository.com/artifact/org.typelevel/cats-core_2.13/2.5.0) to your project, see if it works.

Also, you are trying to use quite internal library. It is possible it has breaking changes without announcement. May I ask if it is possible to use one of [the enrich applications](https://docs.snowplow.io/docs/pipeline-components-and-applications/enrichment-components/) listed in here ?

**Comment by tajdars** [comment]
hi @spenes 

We are trying to upgrade an existing java app which uses snowplow 0.38.0 as a library dependency. Switching from this to snowplow as an app (configurable I understand) will be a very major change.

Any reference java app / piece_of_code / test_client will be very helpful here.

**Comment by spenes** [comment]
Unfortunately we don't have any example like that since we don't use any Java in Snowplow. Due to the reasons I gave previously, it might not even possible to use it in the Java at the moment. Even it is possible, it would still be very major change on your application going from 3 years old 0.38.0 version to current version. 

If you are trying modernize your setup, we can support you better if you use our published applications instead of internal libraries.

**Comment by tajdars** [comment]
hi @spenes , is the licensing Apache-2 for snowplow dockerised enricher apps ?

**Comment by spenes** [comment]
Yes, it is [licensed under Apache 2](https://github.com/snowplow/enrich#copyright-and-license).

**Comment by tajdars** [comment]
hi @spenes ,  

In the scenario running snowplow enrich as a jar,  how would we go about modification(s) :

for example outputting to kafka and an additional custom sink.

I suppose the scala code could be modified locally ?

**Comment by spenes** [comment]
There are [separate sub-modules for different streaming tools in Enrich repo](https://github.com/snowplow/enrich/tree/master/modules). You can either update the existing ones or create new one with following the same pattern in existing modules.

By the way, we have [Enrich application for Kafka](https://docs.snowplow.io/docs/pipeline-components-and-applications/enrichment-components/enrich-kafka/). You can find more information in [the docs](https://docs.snowplow.io/docs/pipeline-components-and-applications/enrichment-components/enrich-kafka/).

**Comment by benjben** [comment]
Hi @tajdars , to add to what Enes said, you might be interested in [Snowbridge](https://github.com/snowplow/snowbridge), which makes it possible to copy the enriched stream (or any stream) from a queue to another queue. For instance you could route the enriched events from Kinesis to Kafka, or the other way around.
