### ISSUE TITLE
Update the LookML folders/files to match JSON Schema pathing/vendoring

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#769]
Unscheduled as it's quite helpful for LookMLs to be in a flat folder structure for now.

**Comment by paulboocock** [comment]
Closing as we're currently not maintaining our existing LookML models. Once the work is complete on our new and updated data models, revisiting our LookML support (which will be a complete rebuild) might be on the cards.

It's worth noting though, that Looker has also completely rebuilt how their folders and structure works since this issue was first created.
