### ISSUE TITLE
Hadoop Elasticsearch Sink: load bad rows into Elasticsearch

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#824]
We can use ElasticSearch as a monitoring tool to keep track of the number of bad rows generated with each run, and drill into the data to understand the causes of those errors.

**Comment by alexanderdean** [comment]
Bringing this forward. Talk to Alex when ready to do this one - I have some ideas!

**Comment by fblundun** [comment]
* https://www.elastic.co/guide/en/elasticsearch/hadoop/current/cascading.html
* https://github.com/elastic/elasticsearch-hadoop
* https://github.com/Cascading/cascading.elasticsearch
* https://github.com/scalding-io/scalding-taps
* https://github.com/scalding-io/ProgrammingWithScalding

**Comment by fblundun** [comment]
Should this job have an optional exceptions folder like the others?

**Comment by alexanderdean** [comment]
Yes please Fred

**Comment by fblundun** [comment]
I have been getting `org.elasticsearch.index.mapper.MapperParsingException: failed to parse` errors from Elasticsearch. The reason for this is that I was using testing with old-style enriched bad rows with string errors instead of processing messages. The job would first send the enriched bad rows to ES, causing ES to infer this mapping:

```json
      "badrows" : {
        "properties" : {
          "errors" : {
            "type" : "string"
          },
          "line" : {
            "type" : "string"
          }
        }
      }
```

If I send in the shred bad rows (which use processing messages) first, this is the inferred mapping:

```json
      "shredded" : {
        "properties" : {
          "errors" : {
            "properties" : {
              "level" : {
                "type" : "string"
              },
              "message" : {
                "type" : "string"
              },
              "repositories" : {
                "type" : "string"
              }
            }
          },
          "line" : {
            "type" : "string"
          }
        }
      }
```

Sending one before the other causes a mapper failure as neither fits the other's mapping.

Should we only support new-style enrich bad rows with processing messages rather than strings?

If not, we need to either put the two different types of failure in different types or indexes or create a predefined mapping which allows the errors to be either strings or hashes.

**Comment by fblundun** [comment]
In ES 2.0.0, the two types of bad row (old-style and new-style) would actually have to go in different indexes: https://www.elastic.co/blog/great-mapping-refactoring

**Comment by alexanderdean** [comment]
* In R71 we are moving to new-style bad rows everywhere
* Until R73 we don't have a formal mechanism for loading any bad rows in ES for the Hadoop pipeline
* For a while we have had a formal mechanism for loading bad rows into ES for the Kinesis pipeline, this only loaded old-style bad rows because the new style were previously only in Hadoop Shred
* If we only support new-style bad rows then the only issue will be for Kinesis pipeline users who have old-style bad rows already loaded in ES - for these users, they will have to setup a new index in ES for the new-style

Thereforce: this is only a Kinesis pipeline upgrade issue - and within the context of this ticket, just supporting new-style is fine.

**Comment by fblundun** [comment]
One more thing: if the "copy to Elasticsearch" step fails halfway through, then rerunning the step will end up creating some duplicates. Is this acceptable?

If not there are some alternatives to explore:

* Have the job actually parse the bad row JSON strings and add an extra field which is a hash of the whole JSON. This hash would be used as the ES document ID of the bad row. It wouldn't actually need to go into the document (see https://github.com/elastic/elasticsearch-hadoop/issues/230).

* Add a UUID to all our bad rows.

* Have some sort of Elasticsearch rotation system. For instance, write bad rows to a temporary index and when the EMR succeeds copy them to the main index.

**Comment by alexanderdean** [comment]
Some dupes is acceptable for release - can you add the alternatives into a new ticket called "Explore options for ..."

**Comment by alexanderdean** [comment]
Note that we are currently trying to get this working with AWS Elasticsearch Service - but that is blocked currently, see https://github.com/elastic/elasticsearch-hadoop/issues/565#issuecomment-146244371
