### ISSUE TITLE
Scala Hadoop Enrich: add .forceToDisk to common to speed up run

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#859]
https://groups.google.com/forum/#!msg/cascading-user/dxYcLWJGS0U/kVh3UiLTpi8J

https://github.com/twitter/scalding/blob/0.9.0rc16/scalding-core/src/main/scala/com/twitter/scalding/RichPipe.scala#L481

http://docs.cascading.org/cascading/2.0/javadoc/cascading/pipe/Checkpoint.html

**Comment by alexanderdean** [comment]
This is much more important now that we have costly enrichments such as API lookups.

**Comment by fblundun** [comment]
If I understand correctly, the problem is that the "common" pipe gets run twice - once to find good events and once to find bad events.

But when I run the any test from the Hadoop Enrich test suite, these three lines get run once per event each (based on extra logging statements I inserted):

Common: https://github.com/snowplow/snowplow/blob/60adc9b7192a032b97a2f65706b12f7890046787/3-enrich/scala-hadoop-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich.hadoop/EtlJob.scala#L172
Bad: https://github.com/snowplow/snowplow/blob/60adc9b7192a032b97a2f65706b12f7890046787/3-enrich/scala-hadoop-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich.hadoop/EtlJob.scala#L178
Good: https://github.com/snowplow/snowplow/blob/60adc9b7192a032b97a2f65706b12f7890046787/3-enrich/scala-hadoop-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich.hadoop/EtlJob.scala#L191

So the "common" pipe seems to be run once rather than twice. Am I misunderstanding something?

**Comment by alexanderdean** [comment]
I think there are two scenarios:

1. The recent Cascading upgrade does this optimisation for free
2. The test suite isn't reflecting how a real Hadoop cluster will run this

One way of investigating would be to compare job times with and without
this .forceToDisk...

**Comment by fblundun** [comment]
I just tried the same thing with the r60 tag, and got the same result. So it probably wasn't due to the Cascading update.

**Comment by fblundun** [comment]
Looks like this does indeed speed things up!

I added a line to log a message to stdout for every enriched event. Then I ran Hadoop Enrich with and without forceToDisk, each time with just one event as input.

For each job, I downloaded the logs for the cluster and grepped for the log message. With forceToDisk, the message appeared 3 times. Without forceToDisk, it appeared 6 times.

**Comment by alexanderdean** [comment]
Fantastic news!
