### ISSUE TITLE
Scala Common Enrich: support "pii" annotations in schemas for PII Enrichment

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#860]
PII = Personally Identifiable Information

The basic idea:
- Any JSON Schema (ue or context) can be annotated with `"pii": true` on a per-property basis
- If this PII Scrubber is turned on, then we encrypt any given PII property in any JSON, using AES - so you end up with a unique but non-PII value, e.g. "Fred Blundun" always -> "1de6e53cb23"

This would be of potential interest to users in healthcare or finance, where the ability for analysts to drill down to individual users could be a privacy concern

/cc @yalisassoon @fblundun

**Comment by christoph-buente** [comment]
I generally like the idea of getting rid of PII, because it might be a legal requirement. However, if it does not happen in the tracker (specifically the JS tracker), users could still see that PII is transferered to the collector. Using the clojure collector ensures the PII ends up in disk in the log files.

So i created #465 to allow to encrypt data before it is being send off. I think a key is not nessecarily needed to encrypt data like names or email addresses. MD5, SHA1, SHA256 are the industry standards and are widely used. Wouldn't it be sufficient if we could apply a scrubber/anonymizer as a callback function to the formTracking?

**Comment by alexanderdean** [comment]
I agree that PII scrubbing (or hashing or encryption) in the trackers is preferable, as anything we do in the enrichment process is basically "too late" from the raw logs perspective.

But I'll keep this open because it would be nice to have this available, especially for applying retrospective scrubbing in the case that something sensitive slipped through a tracker...

**Comment by alexanderdean** [comment]
Renamed so that it follows on from https://github.com/snowplow/snowplow/issues/3472

**Comment by alexanderdean** [comment]
One of the nice things about this idea is that the pii: true hint would be enough for Iglu when generating Redshift etc tables to make sure these columns are wide enough to take the hashed value.

It also just means that the work to identify that e.g. com.acme.email/send_email's email_recipient property is PII is just done in one place (at the time of schema authorship), rather than every user having to configure their own PII Enrichment.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/212
