### ISSUE TITLE
Scala Common Enrich: add cookie extractor enrichment

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#998]
For companies using the Scala Stream Collector on a first-party domain, it would be neat to have an enrichment which could:

* Take a list of cookies you were interested in
* Generate a context for each cookie. Each cookie would have the same structure: name & value

This is neat because companies often have valuable info (e.g. about CMS sessions etc) in their first-party cookies.

This would only work currently for the Scala Stream Collector (only collector which records headers and thus cookies).

**Comment by kazjote** [comment]
I am working on it. These are my propsed json schemas:

https://github.com/snowplow/iglu-central/compare/master...RetentionGrid:cookie_extractor?expand=1

**Comment by fblundun** [comment]
I think the cookie_extractor config schema looks good.

For the cookie_extractor_context - should have one context per cookie rather than all cookies in a single context? I think this would be more elegant in Redshift since we would avoid having a field containing a raw literal JSON array string.

Thoughts @yalisassoon ?

**Comment by alexanderdean** [comment]
Duplicate of #2072
